from typing import Callable

from ._core import AppContext

def context() -> AppContext: ...
def set_editor_tick_callback(callback: Callable[[float], None] | None) -> None: ...
def clear_editor_tick_callback() -> None: ...
def set_editor_physics_callback(callback: Callable[[float], None] | None) -> None: ...
def clear_editor_physics_callback() -> None: ...

__all__: list[str]
