from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Mapping, Sequence

import numpy as np

from ._core import AppContext, PhysicsBackendType

ArrayLike = Sequence[float] | np.ndarray


@dataclass(frozen=True)
class VectorSpec:
    names: tuple[str, ...]
    lower_bounds: tuple[float, ...]
    upper_bounds: tuple[float, ...]
    units: tuple[str, ...] = ...
    version: str = ...
    @property
    def shape(self) -> tuple[int]: ...
    @property
    def size(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> VectorSpec: ...


class VectorSpace:
    low: np.ndarray
    high: np.ndarray
    shape: tuple[int, ...]
    dtype: Any
    names: list[str]
    units: list[str]
    def __init__(
        self,
        low: Sequence[float],
        high: Sequence[float],
        *,
        names: Sequence[str] | None = None,
        units: Sequence[str] | None = None,
        seed: int | None = None,
    ) -> None: ...
    def sample(self) -> np.ndarray: ...
    def contains(self, value: ArrayLike) -> bool: ...


def space_from_spec(spec: VectorSpec | Mapping[str, Any]) -> VectorSpace: ...


@dataclass
class EnvConfig:
    scene: str = ...
    backend: str | PhysicsBackendType = ...
    num_envs: int = ...
    physics_dt: float = ...
    decimation: int = ...
    episode_length_s: float = ...
    robot: str | None = ...
    controlled_joints: tuple[str, ...] | None = ...
    auto_reset: bool = ...
    project_path: str | None = ...
    simulation: Mapping[str, Any] = ...
    @classmethod
    def from_mapping(cls, value: Mapping[str, Any] | None) -> EnvConfig: ...


class ActionManager:
    spec: VectorSpec
    last_action: np.ndarray
    def process_action(self, action: ArrayLike) -> np.ndarray: ...
    def apply_action(self, processed_action: np.ndarray) -> None: ...


class ObservationManager:
    spec: VectorSpec
    def compute(self) -> np.ndarray: ...


class RewardManager:
    def __init__(self, env: ManagerBasedEnv, terms: Sequence[Callable[[ManagerBasedEnv], ArrayLike]] | None = None) -> None: ...
    def compute(self) -> np.ndarray: ...


class TerminationManager:
    def __init__(self, env: ManagerBasedEnv, conditions: Sequence[Callable[[ManagerBasedEnv], ArrayLike]] | None = None) -> None: ...
    def compute(self) -> tuple[np.ndarray, np.ndarray]: ...


class EventManager:
    def reset(self, env_ids: np.ndarray) -> None: ...


class CommandManager:
    def reset(self, env_ids: np.ndarray) -> None: ...


class Recorder:
    episode_returns: list[float]
    episode_lengths: list[int]
    def record_done(self, returns: np.ndarray, lengths: np.ndarray, done: np.ndarray) -> None: ...


class Metrics(dict): ...


class ManagerBasedEnv:
    cfg: EnvConfig
    context: AppContext
    num_envs: int
    physics_dt: float
    decimation: int
    env_dt: float
    max_episode_steps: int
    auto_reset: bool
    robot_name: str
    episode_lengths: np.ndarray
    episode_returns: np.ndarray
    action_manager: ActionManager
    observation_manager: ObservationManager
    reward_manager: RewardManager
    termination_manager: TerminationManager
    event_manager: EventManager
    command_manager: CommandManager
    recorder: Recorder
    metrics: Metrics
    def __init__(self, cfg: Mapping[str, Any] | EnvConfig | None = None, *, context: AppContext | None = None) -> None: ...
    @property
    def observation_spec(self) -> VectorSpec: ...
    @property
    def action_spec(self) -> VectorSpec: ...
    @property
    def observation_space(self) -> VectorSpace: ...
    @property
    def action_space(self) -> VectorSpace: ...
    def reset(self, seed: int | None = None, options: Mapping[str, Any] | None = None) -> tuple[np.ndarray, dict[str, Any]]: ...
    def step(self, action: ArrayLike) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict[str, Any]]: ...
    def close(self) -> None: ...


class VectorEnv(ManagerBasedEnv): ...


class GymWrapper:
    metadata: dict[str, Any]
    observation_space: VectorSpace
    action_space: VectorSpace
    def __init__(self, env: ManagerBasedEnv) -> None: ...
    def reset(self, *, seed: int | None = None, options: Mapping[str, Any] | None = None): ...
    def step(self, action: ArrayLike): ...
    def close(self) -> None: ...
    @property
    def unwrapped(self) -> ManagerBasedEnv: ...


class RslRlVecEnvWrapper:
    env: ManagerBasedEnv
    num_envs: int
    num_obs: int
    num_actions: int
    def __init__(self, env: ManagerBasedEnv) -> None: ...
    def get_observations(self): ...
    def reset(self): ...
    def step(self, actions): ...


__all__: list[str]
