#!/usr/bin/env python3

from __future__ import annotations

import argparse
from concurrent.futures import Future, ThreadPoolExecutor
from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import sys
import threading
from typing import Any, Callable, Sequence
import urllib.error
import urllib.parse
import urllib.request


REVISION = "261cd1f429619d8ef4f546bd788ab9dea906b5e1"
MANIFEST_PATH = Path(__file__).with_name("asset_manifest.json")
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "assets"
DEFAULT_PROJECT_DIR = Path(__file__).resolve().parent
SOURCE_USD = PurePosixPath(
    "unitree_g1/usd/g1_isaac.usd"
)
GENERATED_SCENE = PurePosixPath("generated/g1_29dof.jscn")
GENERATED_SCENE_STAMP = PurePosixPath("generated/g1_29dof.import.json")
SCENE_CACHE_VERSION = 7
DEFAULT_BASE_URLS = (
    f"https://raw.githubusercontent.com/newton-physics/newton-assets/{REVISION}",
    f"https://cdn.jsdelivr.net/gh/newton-physics/newton-assets@{REVISION}",
)
GITHUB_BLOB_API = "https://api.github.com/repos/newton-physics/newton-assets/git/blobs"
GITHUB_RAW_SIZE_LIMIT = 20 * 1024 * 1024
CHUNK_SIZE = 256 * 1024
NETWORK_TIMEOUT_SECONDS = 45
RETRIES_PER_URL = 3
DEFAULT_JOBS = 4
_GIT_SHA1_PATTERN = re.compile(r"[0-9a-f]{40}")


@dataclass(frozen=True)
class Asset:
    path: str
    size: int
    git_blob_sha1: str


class DownloadError(RuntimeError):
    pass


def load_manifest(path: Path = MANIFEST_PATH) -> tuple[Asset, ...]:
    document = json.loads(path.read_text(encoding="utf-8"))
    if document.get("revision") != REVISION:
        raise ValueError(
            f"asset manifest revision must be {REVISION}, got {document.get('revision')!r}"
        )

    assets: list[Asset] = []
    seen_paths: set[str] = set()
    for entry in document.get("files", []):
        relative_path = entry.get("path")
        size = entry.get("size")
        blob_sha1 = entry.get("git_blob_sha1")
        if not isinstance(relative_path, str):
            raise ValueError("asset path must be a string")
        parts = PurePosixPath(relative_path)
        if parts.is_absolute() or ".." in parts.parts or not parts.parts:
            raise ValueError(f"unsafe asset path: {relative_path!r}")
        if parts.parts[0] != "unitree_g1":
            raise ValueError(f"asset is outside unitree_g1: {relative_path!r}")
        if relative_path in seen_paths:
            raise ValueError(f"duplicate asset path: {relative_path!r}")
        if not isinstance(size, int) or isinstance(size, bool) or size <= 0:
            raise ValueError(f"invalid size for {relative_path!r}: {size!r}")
        if not isinstance(blob_sha1, str) or _GIT_SHA1_PATTERN.fullmatch(blob_sha1) is None:
            raise ValueError(f"invalid Git blob SHA-1 for {relative_path!r}: {blob_sha1!r}")
        seen_paths.add(relative_path)
        assets.append(Asset(relative_path, size, blob_sha1))

    if not assets:
        raise ValueError("asset manifest contains no files")
    return tuple(assets)


ASSETS = load_manifest()
TOTAL_BYTES = sum(asset.size for asset in ASSETS)


def scene_cache_identity(gobot_version: str, assets: Sequence[Asset] = ASSETS) -> dict[str, Any]:
    digest = hashlib.sha256()
    for asset in sorted(assets, key=lambda entry: entry.path):
        digest.update(asset.path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(str(asset.size).encode("ascii"))
        digest.update(b"\0")
        digest.update(asset.git_blob_sha1.encode("ascii"))
        digest.update(b"\n")
    return {
        "cache_version": SCENE_CACHE_VERSION,
        "gobot_version": gobot_version,
        "newton_assets_revision": REVISION,
        "manifest_sha256": digest.hexdigest(),
        "source": SOURCE_USD.as_posix(),
    }


def _is_valid_external_resource(path: Path) -> bool:
    try:
        if not path.is_file() or path.stat().st_size == 0:
            return False
        file_size = path.stat().st_size
        if path.suffix.lower() != ".ply":
            return True
        data = path.read_bytes()[: 64 * 1024]
    except OSError:
        return False
    header_end = data.find(b"end_header\n")
    if header_end < 0 or header_end + len(b"end_header\n") >= len(data):
        return False
    header = data[:header_end]
    if not header.startswith(b"ply\nformat binary_little_endian 1.0\n") or (
        b"comment Generated by Gobot\n" not in header
    ):
        return False
    vertex_match = re.search(rb"(?:^|\n)element vertex ([1-9][0-9]*)(?:\n|$)", header)
    face_match = re.search(rb"(?:^|\n)element face ([1-9][0-9]*)(?:\n|$)", header)
    if vertex_match is None or face_match is None or face_match.start() <= vertex_match.end():
        return False
    vertex_properties = header[vertex_match.end() : face_match.start()].splitlines()
    property_sizes = {b"uchar": 1, b"float": 4}
    vertex_stride = 0
    for line in vertex_properties:
        fields = line.split()
        if not fields:
            continue
        if len(fields) != 3 or fields[0] != b"property" or fields[1] not in property_sizes:
            return False
        vertex_stride += property_sizes[fields[1]]
    if vertex_stride < 13 or b"property uchar gobot_padding" not in vertex_properties:
        return False
    payload_offset = header_end + len(b"end_header\n")
    expected_size = (
        payload_offset
        + int(vertex_match.group(1)) * vertex_stride
        + int(face_match.group(1)) * (1 + 3 * 4)
    )
    return file_size == expected_size


def is_scene_cache_current(
    scene_path: Path,
    stamp_path: Path,
    identity: dict[str, Any],
    *,
    project_dir: Path | None = None,
) -> bool:
    if not scene_path.is_file() or scene_path.stat().st_size == 0 or not stamp_path.is_file():
        return False
    try:
        stamp = json.loads(stamp_path.read_text(encoding="utf-8"))
        scene = json.loads(scene_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    if stamp != identity:
        return False
    if project_dir is None:
        return True
    for resource in scene.get("__EXT_RESOURCES__", ()):
        path = resource.get("__PATH__")
        if isinstance(path, str) and path.startswith("res://"):
            if not _is_valid_external_resource(
                project_dir / path.removeprefix("res://")
            ):
                return False
    return True


def _resource_path(project_dir: Path, path: Path) -> str:
    try:
        relative = path.resolve().relative_to(project_dir.resolve())
    except ValueError as error:
        raise ValueError(f"generated scene path must be inside {project_dir}") from error
    return "res://" + relative.as_posix()


def _import_usd_with_gobot(project_dir: Path, source_path: Path, scene_path: Path) -> str:
    import gobot

    gobot.set_project_path(str(project_dir))
    source_resource = _resource_path(project_dir, source_path)
    scene_resource = _resource_path(project_dir, scene_path)
    imported = gobot.load_scene(source_resource)
    stack = [imported.root]
    robots = []
    while stack:
        node = stack.pop()
        if node.type_name == "Robot3D":
            robots.append(node)
        stack.extend(reversed(node.children))
    if len(robots) != 1:
        raise RuntimeError(
            f"official G1 USD must import exactly one Robot3D, got {len(robots)}"
        )
    gobot.save_scene(robots[0], scene_resource)
    return str(gobot.__version__)


def ensure_generated_scene(
    project_dir: Path,
    output: Path,
    *,
    gobot_version: str | None = None,
    importer: Callable[[Path, Path, Path], str] | None = None,
    force: bool = False,
) -> bool:
    source_path = output.joinpath(*SOURCE_USD.parts)
    scene_path = output.joinpath(*GENERATED_SCENE.parts)
    stamp_path = output.joinpath(*GENERATED_SCENE_STAMP.parts)
    if not source_path.is_file():
        raise FileNotFoundError(f"official G1 USD is missing: {source_path}")

    if importer is None:
        importer = _import_usd_with_gobot
    if gobot_version is None:
        import gobot

        gobot_version = str(gobot.__version__)
    identity = scene_cache_identity(gobot_version)
    if not force and is_scene_cache_current(
        scene_path, stamp_path, identity, project_dir=project_dir
    ):
        report_progress(1, 1, "G1 Gobot scene cache is current")
        return False

    scene_path.parent.mkdir(parents=True, exist_ok=True)
    stamp_path.unlink(missing_ok=True)
    report_progress(0, 1, "Importing G1 USD into Gobot scene")
    imported_version = importer(project_dir.resolve(), source_path.resolve(), scene_path.resolve())
    if imported_version != gobot_version:
        identity = scene_cache_identity(imported_version)
    if not scene_path.is_file() or scene_path.stat().st_size == 0:
        raise RuntimeError(f"Gobot did not produce a scene at {scene_path}")
    temporary_stamp = stamp_path.with_name(stamp_path.name + ".part")
    temporary_stamp.write_text(
        json.dumps(identity, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    temporary_stamp.replace(stamp_path)
    report_progress(1, 1, "Imported G1 USD into Gobot scene")
    return True


def git_blob_sha1(path: Path) -> str:
    size = path.stat().st_size
    digest = hashlib.sha1(usedforsecurity=False)
    digest.update(f"blob {size}\0".encode("ascii"))
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(CHUNK_SIZE), b""):
            digest.update(block)
    return digest.hexdigest()


def is_valid(path: Path, asset: Asset) -> bool:
    return (
        path.is_file()
        and path.stat().st_size == asset.size
        and git_blob_sha1(path) == asset.git_blob_sha1
    )


def report_progress(current: int, total: int, message: str) -> None:
    if "GOBOT_PROJECT_HOOK" in os.environ:
        payload = json.dumps(
            {"current": current, "total": total, "message": message},
            separators=(",", ":"),
        )
        print(f"GOBOT_PROGRESS {payload}", flush=True)
        return

    completed_mib = current / (1024 * 1024)
    total_mib = total / (1024 * 1024)
    print(
        f"\r{message}: {completed_mib:.1f} / {total_mib:.1f} MiB",
        end="",
        flush=True,
    )


class AggregateProgress:
    def __init__(self, assets: Sequence[Asset]) -> None:
        self._sizes = tuple(asset.size for asset in assets)
        self._reported = [0] * len(assets)
        self._current = 0
        self._total = sum(self._sizes)
        self._lock = threading.Lock()

    def update(self, index: int, current: int, message: str) -> None:
        bounded = min(max(current, 0), self._sizes[index])
        with self._lock:
            previous = self._reported[index]
            if bounded > previous:
                self._reported[index] = bounded
                self._current += bounded - previous
            report_progress(self._current, self._total, message)


def asset_url(base_url: str, asset: Asset) -> str:
    encoded_path = urllib.parse.quote(asset.path, safe="/")
    return f"{base_url.rstrip('/')}/{encoded_path}"


def asset_urls(base_urls: Sequence[str], asset: Asset) -> tuple[str, ...]:
    urls = tuple(asset_url(base_url, asset) for base_url in base_urls)
    if tuple(base_urls) == DEFAULT_BASE_URLS and asset.size > GITHUB_RAW_SIZE_LIMIT:
        # GitHub raw and jsDelivr reject repository blobs above their normal
        # size limits. The Git blobs endpoint serves the pinned object directly.
        return (f"{GITHUB_BLOB_API}/{asset.git_blob_sha1}", *urls)
    return urls


def _response_status(response: Any) -> int | None:
    status = getattr(response, "status", None)
    if status is None and hasattr(response, "getcode"):
        status = response.getcode()
    return status


def download_from_url(
    url: str,
    destination: Path,
    asset: Asset,
    *,
    progress: Callable[[int], None],
    opener: Callable[..., Any] | None = None,
) -> None:
    if opener is None:
        opener = urllib.request.urlopen

    existing_size = destination.stat().st_size if destination.is_file() else 0
    if existing_size >= asset.size:
        destination.unlink(missing_ok=True)
        existing_size = 0

    headers = {"User-Agent": "Gobot Newton G1 asset downloader"}
    if url.startswith(f"{GITHUB_BLOB_API}/"):
        headers["Accept"] = "application/vnd.github.raw+json"
    if existing_size:
        headers["Range"] = f"bytes={existing_size}-"
    request = urllib.request.Request(url, headers=headers)

    with opener(request, timeout=NETWORK_TIMEOUT_SECONDS) as response:
        status = _response_status(response)
        append = existing_size > 0 and status == 206
        if append:
            content_range = response.headers.get("Content-Range", "")
            if not content_range.startswith(f"bytes {existing_size}-"):
                raise RuntimeError(f"unexpected Content-Range: {content_range!r}")
        else:
            existing_size = 0

        received = existing_size
        remaining = asset.size - received
        content_length = response.headers.get("Content-Length")
        if content_length is not None:
            try:
                response_size = int(content_length)
            except ValueError as error:
                raise RuntimeError(f"invalid Content-Length: {content_length!r}") from error
            if response_size > remaining:
                raise RuntimeError(
                    f"response exceeds expected size: {response_size} > {remaining}"
                )

        mode = "ab" if append else "wb"
        with destination.open(mode) as stream:
            while block := response.read(CHUNK_SIZE):
                if len(block) > asset.size - received:
                    raise RuntimeError(
                        f"response exceeds expected size after {received} bytes"
                    )
                stream.write(block)
                received += len(block)
                progress(received)

    if received != asset.size:
        raise RuntimeError(f"incomplete response: expected {asset.size}, got {received}")


def _target_path(output: Path, asset: Asset) -> Path:
    return output.joinpath(*PurePosixPath(asset.path).parts)


def _install_asset(
    output: Path,
    asset: Asset,
    *,
    index: int,
    asset_count: int,
    base_urls: Sequence[str],
    force: bool,
    opener: Callable[..., Any] | None,
    aggregate_progress: AggregateProgress,
) -> None:
    target = _target_path(output, asset)
    temporary = target.with_name(target.name + ".part")
    target.parent.mkdir(parents=True, exist_ok=True)
    message = f"Downloading G1 assets ({index + 1}/{asset_count}): {target.name}"

    def progress(current: int) -> None:
        aggregate_progress.update(index, current, message)

    if not force and is_valid(target, asset):
        progress(asset.size)
        return

    if force:
        temporary.unlink(missing_ok=True)
    elif is_valid(temporary, asset):
        temporary.replace(target)
        progress(asset.size)
        return
    elif temporary.is_file() and temporary.stat().st_size >= asset.size:
        temporary.unlink()

    failures: list[str] = []
    for attempt in range(1, RETRIES_PER_URL + 1):
        for url in asset_urls(base_urls, asset):
            try:
                download_from_url(
                    url,
                    temporary,
                    asset,
                    progress=progress,
                    opener=opener,
                )
                actual_sha1 = git_blob_sha1(temporary)
                if actual_sha1 != asset.git_blob_sha1:
                    temporary.unlink()
                    raise RuntimeError(
                        "Git blob SHA-1 mismatch: "
                        f"expected {asset.git_blob_sha1}, got {actual_sha1}"
                    )
                temporary.replace(target)
                progress(asset.size)
                return
            except (OSError, RuntimeError, urllib.error.URLError) as error:
                failures.append(f"{url} (attempt {attempt}/{RETRIES_PER_URL}): {error}")

    detail = "\n  ".join(failures)
    raise DownloadError(f"failed to download {asset.path}:\n  {detail}")


def install_assets(
    output: Path,
    *,
    assets: Sequence[Asset] = ASSETS,
    base_urls: Sequence[str] = DEFAULT_BASE_URLS,
    force: bool = False,
    opener: Callable[..., Any] | None = None,
    jobs: int = DEFAULT_JOBS,
) -> None:
    if not assets:
        raise ValueError("assets must not be empty")
    if not base_urls:
        raise ValueError("base_urls must not be empty")
    if not isinstance(jobs, int) or isinstance(jobs, bool) or jobs <= 0:
        raise ValueError("jobs must be a positive integer")
    if len({asset.path for asset in assets}) != len(assets):
        raise ValueError("asset paths must be unique")

    output.mkdir(parents=True, exist_ok=True)
    asset_count = len(assets)
    aggregate_progress = AggregateProgress(assets)
    stop_event = threading.Event()
    futures: list[Future[None]] = []
    errors: list[Exception] = []

    def install_one(index: int, asset: Asset) -> None:
        if stop_event.is_set():
            return
        try:
            _install_asset(
                output,
                asset,
                index=index,
                asset_count=asset_count,
                base_urls=base_urls,
                force=force,
                opener=opener,
                aggregate_progress=aggregate_progress,
            )
        except Exception:
            stop_event.set()
            raise

    with ThreadPoolExecutor(max_workers=min(jobs, asset_count)) as executor:
        for index, asset in enumerate(assets):
            futures.append(executor.submit(install_one, index, asset))
        for future in futures:
            try:
                future.result()
            except Exception as error:
                errors.append(error)

    if errors:
        raise errors[0]

    if "GOBOT_PROJECT_HOOK" not in os.environ:
        print()


def positive_int(value: str) -> int:
    try:
        parsed = int(value)
    except ValueError as error:
        raise argparse.ArgumentTypeError("must be a positive integer") from error
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Download the pinned Newton G1 USD and policy, then cache its Gobot scene."
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--base-url",
        action="append",
        dest="base_urls",
        help="Override the asset mirror base URL (may be repeated).",
    )
    parser.add_argument(
        "--jobs",
        type=positive_int,
        default=DEFAULT_JOBS,
        help=f"Maximum concurrent downloads (default: {DEFAULT_JOBS}).",
    )
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    output = args.output.expanduser().resolve()
    try:
        environment_url = os.environ.get("GOBOT_NEWTON_ASSET_BASE_URL")
        base_urls = tuple(args.base_urls or ((environment_url,) if environment_url else DEFAULT_BASE_URLS))
        install_assets(output, base_urls=base_urls, force=args.force, jobs=args.jobs)
        project_dir = DEFAULT_PROJECT_DIR if output == DEFAULT_OUTPUT else output.parent
        ensure_generated_scene(project_dir, output, force=args.force)
    except (ImportError, OSError, RuntimeError, ValueError) as error:
        print(f"G1 asset setup failed: {error}", file=sys.stderr)
        partials = sorted(output.rglob("*.part")) if output.is_dir() else []
        for partial in partials:
            print(f"Partial download retained for retry: {partial}", file=sys.stderr)
        return 1

    print(f"Verified {len(ASSETS)} G1 assets and generated scene in {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
