from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Mapping, Sequence

import numpy as np

from .._core import AppContext, PhysicsBackendType

ArrayLike = Sequence[float] | np.ndarray


@dataclass(frozen=True)
class VectorSpec:
    names: tuple[str, ...]
    lower_bounds: tuple[float, ...]
    upper_bounds: tuple[float, ...]
    units: tuple[str, ...] = ...
    version: str = ...
    @property
    def shape(self) -> tuple[int]: ...
    @property
    def size(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, value: Mapping[str, Any]) -> VectorSpec: ...


class VectorSpace:
    low: np.ndarray
    high: np.ndarray
    shape: tuple[int, ...]
    dtype: Any
    names: list[str]
    units: list[str]
    def __init__(
        self,
        low: Sequence[float],
        high: Sequence[float],
        *,
        names: Sequence[str] | None = None,
        units: Sequence[str] | None = None,
        seed: int | None = None,
    ) -> None: ...
    def sample(self) -> np.ndarray: ...
    def contains(self, value: ArrayLike) -> bool: ...


def space_from_spec(spec: VectorSpec | Mapping[str, Any]) -> VectorSpace: ...


@dataclass(frozen=True)
class ManagerTermConfig:
    name: str
    type: str
    weight: float = ...
    enabled: bool = ...
    params: Mapping[str, Any] = ...
    @classmethod
    def from_mapping(cls, value: str | Mapping[str, Any], *, default_name: str = ...) -> ManagerTermConfig: ...
    def to_dict(self) -> dict[str, Any]: ...


@dataclass
class EnvConfig:
    scene: str = ...
    backend: str | PhysicsBackendType = ...
    num_envs: int = ...
    physics_dt: float = ...
    decimation: int = ...
    episode_length_s: float = ...
    robot: str | None = ...
    controlled_joints: tuple[str, ...] | None = ...
    auto_reset: bool = ...
    project_path: str | None = ...
    simulation: Mapping[str, Any] = ...
    actions: Mapping[str, Any] = ...
    observations: Mapping[str, Any] = ...
    rewards: Mapping[str, Any] = ...
    terminations: Mapping[str, Any] = ...
    events: Mapping[str, Any] = ...
    commands: Mapping[str, Any] = ...
    @classmethod
    def from_mapping(cls, value: Mapping[str, Any] | None) -> EnvConfig: ...
    def to_dict(self) -> dict[str, Any]: ...


@dataclass
class TaskConfig:
    name: str = ...
    scene: str = ...
    backend: str | PhysicsBackendType = ...
    num_envs: int = ...
    physics_dt: float = ...
    decimation: int = ...
    episode_length_s: float = ...
    robot: str | None = ...
    project_path: str | None = ...
    auto_reset: bool = ...
    actions: Mapping[str, Any] = ...
    observations: Mapping[str, Any] = ...
    rewards: Mapping[str, Any] = ...
    terminations: Mapping[str, Any] = ...
    events: Mapping[str, Any] = ...
    commands: Mapping[str, Any] = ...
    simulation: Mapping[str, Any] = ...
    metadata: Mapping[str, Any] = ...
    @classmethod
    def from_mapping(cls, value: Mapping[str, Any] | None) -> TaskConfig: ...
    @classmethod
    def from_file(cls, path: str | Path) -> TaskConfig: ...
    def env_config(self) -> EnvConfig: ...
    def to_dict(self) -> dict[str, Any]: ...


def load_task_config(path: str | Path) -> TaskConfig: ...
def make_cartpole_target_task(
    *,
    scene: str = ...,
    backend: str | PhysicsBackendType = ...,
    robot: str = ...,
    project_path: str | None = ...,
    slider_joint: str = ...,
    hinge_joint: str = ...,
    target_cart_position: float = ...,
    randomize_target_position: bool = ...,
    target_cart_position_range: tuple[float, float] = ...,
    max_episode_steps: int = ...,
    physics_dt: float = ...,
    decimation: int = ...,
    force_limit: float = ...,
    pole_angle_limit: float = ...,
    cart_position_limit: float = ...,
    target_tolerance: float = ...,
    target_near_tolerance: float = ...,
    target_velocity_tolerance: float = ...,
    target_overspeed_limit: float = ...,
    fast_reach_bonus: float = ...,
    initial_angle: float = ...,
    initial_cart_position: float = ...,
    randomize_initial_angle: bool = ...,
    disturbance_force_std: float = ...,
    disturbance_impulse_probability: float = ...,
    disturbance_impulse_force: float = ...,
    disturbance_impulse_steps: int = ...,
    num_envs: int = ...,
) -> TaskConfig: ...


class ActionManager:
    spec: VectorSpec
    last_action: np.ndarray
    def process_action(self, action: ArrayLike) -> np.ndarray: ...
    def apply_action(self, processed_action: np.ndarray) -> None: ...


class ObservationManager:
    spec: VectorSpec
    group_specs: dict[str, VectorSpec]
    default_group: str
    def compute(self, group: str | None = None) -> np.ndarray: ...
    def compute_groups(self) -> dict[str, np.ndarray]: ...


class RewardManager:
    last_breakdown: dict[str, np.ndarray]
    def __init__(
        self,
        env: ManagerBasedEnv,
        reward_cfg: Mapping[str, Any] | None = None,
        terms: Sequence[Callable[[ManagerBasedEnv], ArrayLike]] | None = None,
    ) -> None: ...
    def compute(self) -> np.ndarray: ...


class TerminationManager:
    last_reasons: dict[str, np.ndarray]
    def __init__(
        self,
        env: ManagerBasedEnv,
        termination_cfg: Mapping[str, Any] | None = None,
        conditions: Sequence[Callable[[ManagerBasedEnv], ArrayLike]] | None = None,
    ) -> None: ...
    def compute(self) -> tuple[np.ndarray, np.ndarray]: ...


class EventManager:
    def reset(self, env_ids: np.ndarray) -> None: ...
    def sample_effort_disturbance(self, joint: str) -> float: ...


class CommandManager:
    values: dict[str, np.ndarray]
    def reset(self, env_ids: np.ndarray) -> None: ...
    def value(self, name: str) -> np.ndarray: ...
    def to_info(self) -> dict[str, np.ndarray]: ...


class Recorder:
    episode_returns: list[float]
    episode_lengths: list[int]
    def record_done(self, returns: np.ndarray, lengths: np.ndarray, done: np.ndarray) -> None: ...


class Metrics(dict): ...


class ManagerBasedEnv:
    task_config: TaskConfig | None
    cfg: EnvConfig
    context: AppContext
    num_envs: int
    physics_dt: float
    decimation: int
    env_dt: float
    max_episode_steps: int
    auto_reset: bool
    robot_name: str
    episode_lengths: np.ndarray
    episode_returns: np.ndarray
    action_manager: ActionManager
    observation_manager: ObservationManager
    reward_manager: RewardManager
    termination_manager: TerminationManager
    event_manager: EventManager
    command_manager: CommandManager
    recorder: Recorder
    metrics: Metrics
    def __init__(self, cfg: Mapping[str, Any] | EnvConfig | TaskConfig | None = None, *, context: AppContext | None = None) -> None: ...
    @property
    def observation_spec(self) -> VectorSpec: ...
    @property
    def action_spec(self) -> VectorSpec: ...
    @property
    def observation_space(self) -> VectorSpace: ...
    @property
    def action_space(self) -> VectorSpace: ...
    def observation_group_spec(self, group: str) -> VectorSpec: ...
    def reset(self, seed: int | None = None, options: Mapping[str, Any] | None = None) -> tuple[np.ndarray, dict[str, Any]]: ...
    def step(self, action: ArrayLike) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict[str, Any]]: ...
    def close(self) -> None: ...

class VectorEnv:
    task_config: TaskConfig | None
    cfg: EnvConfig
    num_envs: int
    batch_size: int
    num_workers: int
    physics_dt: float
    decimation: int
    env_dt: float
    max_episode_steps: int
    auto_reset: bool
    observation_spec: VectorSpec
    critic_observation_spec: VectorSpec
    action_spec: VectorSpec
    episode_lengths: np.ndarray
    episode_returns: np.ndarray
    def __init__(self, cfg: Mapping[str, Any] | EnvConfig | TaskConfig | None = None) -> None: ...
    @property
    def observation_space(self) -> VectorSpace: ...
    @property
    def action_space(self) -> VectorSpace: ...
    def observation_group_spec(self, group: str) -> VectorSpec: ...
    def reset(
        self,
        seed: int | None = None,
        options: Mapping[str, Any] | None = None,
        env_ids: Sequence[int] | np.ndarray | None = None,
    ) -> tuple[np.ndarray, dict[str, Any]]: ...
    def step(
        self,
        action: ArrayLike,
        env_ids: Sequence[int] | np.ndarray | None = None,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict[str, Any]]: ...
    def async_reset(self) -> None: ...
    def send(self, action: ArrayLike, env_ids: Sequence[int] | np.ndarray | None = None) -> None: ...
    def recv(self) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict[str, Any]]: ...
    def close(self) -> None: ...


class GymWrapper:
    metadata: dict[str, Any]
    observation_space: VectorSpace
    action_space: VectorSpace
    def __init__(self, env: ManagerBasedEnv) -> None: ...
    def reset(self, *, seed: int | None = None, options: Mapping[str, Any] | None = None): ...
    def step(self, action: ArrayLike): ...
    def close(self) -> None: ...
    @property
    def unwrapped(self) -> ManagerBasedEnv: ...


class RslRlVecEnvWrapper:
    env: ManagerBasedEnv | VectorEnv
    num_envs: int
    num_obs: int
    num_privileged_obs: int
    num_actions: int
    max_episode_length: int
    def __init__(self, env: ManagerBasedEnv | VectorEnv, clip_actions: float | None = ..., device: str = ...) -> None: ...
    @property
    def cfg(self): ...
    @property
    def observation_space(self) -> VectorSpace: ...
    @property
    def action_space(self) -> VectorSpace: ...
    @property
    def render_mode(self): ...
    def get_observations(self): ...
    def reset(self): ...
    def step(self, actions): ...
    @property
    def unwrapped(self) -> ManagerBasedEnv | VectorEnv: ...
    def close(self) -> None: ...


class GobotOnPolicyRunner:
    def __init__(self, env: RslRlVecEnvWrapper, train_cfg: Mapping[str, Any], log_dir: str | None = ..., device: str = ...) -> None: ...
    def learn(self, *args: Any, **kwargs: Any): ...
    def save(self, *args: Any, **kwargs: Any): ...
    def load(self, *args: Any, **kwargs: Any): ...


__all__: list[str]
