from __future__ import annotations

from typing import Any, Sequence

class BatchSimulationRuntime:
    context: Any
    robot: str
    base_link: str
    joint_names: tuple[str, ...]
    link_names: tuple[str, ...]
    sensor_names: tuple[str, ...]
    def __init__(self, context: Any, *, robot: str, base_link: str, joint_names: Sequence[str], link_names: Sequence[str] = (), sensor_names: Sequence[str] = ()) -> None: ...
    @property
    def env_count(self) -> int: ...
    def configure(self, num_envs: int) -> None: ...
    def resolved_workers(self, workers: int = 0) -> int: ...
    def step(self, ticks: int, *, workers: int = 0) -> None: ...
    def reset_env(self, env_id: int) -> None: ...
    def set_joint_position_target(self, env_id: int, joint: str, target_position: float) -> None: ...
    def set_joint_position_targets(self, target_positions: Any) -> None: ...
    def reset_joint_state(self, env_id: int, joint: str, position: float, velocity: float = 0.0) -> None: ...
    def reset_link_state(self, env_id: int, link: str, position: Sequence[float], orientation: Sequence[float] = (1.0, 0.0, 0.0, 0.0), linear_velocity: Sequence[float] = (0.0, 0.0, 0.0), angular_velocity: Sequence[float] = (0.0, 0.0, 0.0)) -> None: ...
    def env_state(self, env_id: int) -> Any: ...
    def robot_state(self) -> Any: ...
