from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Sequence

import numpy as np

LOCOMOTION_STEP_PROFILE_NAMES: tuple[str, ...]

class BatchSimulationRuntime:
    context: Any
    robot: str
    base_link: str
    joint_names: tuple[str, ...]
    link_names: tuple[str, ...]
    sensor_names: tuple[str, ...]
    def __init__(
        self,
        context: Any,
        *,
        robot: str,
        base_link: str,
        joint_names: Sequence[str],
        link_names: Sequence[str] = (),
        sensor_names: Sequence[str] = (),
    ) -> None: ...
    @property
    def env_count(self) -> int: ...
    def configure(self, num_envs: int) -> None: ...
    def resolved_workers(self, workers: int = 0) -> int: ...
    def step(self, ticks: int, *, workers: int = 0) -> None: ...
    def reset_env(self, env_id: int) -> None: ...
    def set_joint_position_target(self, env_id: int, joint: str, target_position: float) -> None: ...
    def set_joint_position_targets(self, target_positions: Any) -> None: ...
    def reset_joint_state(self, env_id: int, joint: str, position: float, velocity: float = 0.0) -> None: ...
    def reset_link_state(
        self,
        env_id: int,
        link: str,
        position: Sequence[float],
        orientation: Sequence[float] = (1.0, 0.0, 0.0, 0.0),
        linear_velocity: Sequence[float] = (0.0, 0.0, 0.0),
        angular_velocity: Sequence[float] = (0.0, 0.0, 0.0),
    ) -> None: ...
    def env_state(self, env_id: int) -> Any: ...
    def robot_state(self) -> Any: ...
    def step_and_robot_state(self, target_positions: Any, ticks: int, *, workers: int = 0) -> Any: ...
    def reset_robot_states(
        self,
        env_ids: Sequence[int],
        *,
        base_positions: Any,
        base_orientations: Any,
        base_linear_velocities: Any,
        base_angular_velocities: Any,
        joint_positions: Any,
        joint_velocities: Any,
        joint_position_targets: Any,
    ) -> None: ...

@dataclass
class GobotSceneBatchState:
    raw: dict[str, Any]
    base_position: np.ndarray
    base_quaternion: np.ndarray
    base_linear_velocity: np.ndarray
    base_angular_velocity: np.ndarray
    joint_position: np.ndarray
    joint_velocity: np.ndarray
    joint_lower_limit: np.ndarray
    joint_upper_limit: np.ndarray
    link_names: tuple[str, ...]
    link_position: np.ndarray
    sensor_names: tuple[str, ...]
    sensor_position: np.ndarray
    sensor_values: np.ndarray
    sensor_value_count: np.ndarray
    sensor_hit: np.ndarray
    sensor_hit_point: np.ndarray
    sensor_hit_normal: np.ndarray

class GobotSceneBatchBackend:
    runtime: BatchSimulationRuntime
    def __init__(self, runtime: BatchSimulationRuntime) -> None: ...
    @property
    def env_count(self) -> int: ...
    @property
    def state(self) -> GobotSceneBatchState: ...
    def configure(self, num_envs: int) -> None: ...
    def resolved_workers(self, workers: int = 0) -> int: ...
    def step(self, ctrl: Any, nsteps: int, *, workers: int = 0) -> dict[str, Any]: ...
    def set_position_targets(self, ctrl: Any) -> None: ...
    def set_joint_position_target(self, env_id: int, joint: str, target_position: float) -> None: ...
    def reset_env(self, env_id: int) -> None: ...
    def reset_joint_state(self, env_id: int, joint: str, position: float, velocity: float = 0.0) -> None: ...
    def reset_link_state(
        self,
        env_id: int,
        link: str,
        position: Sequence[float],
        orientation: Sequence[float] = (1.0, 0.0, 0.0, 0.0),
        linear_velocity: Sequence[float] = (0.0, 0.0, 0.0),
        angular_velocity: Sequence[float] = (0.0, 0.0, 0.0),
    ) -> None: ...
    def reset_robot_states(self, env_ids: Sequence[int], **kwargs: Any) -> None: ...
    def env_state(self, env_id: int) -> Any: ...
    def refresh(self) -> GobotSceneBatchState: ...

@dataclass(frozen=True)
class LocomotionBatchSpec:
    foot_link_names: Sequence[str] = ()
    foot_height_sensor_names: Sequence[str] = ()
    foot_contact_sensor_names: Sequence[str] = ()
    height_scan_sensor: str | None = None
    thigh_link_patterns: Sequence[str] = ()
    shank_link_patterns: Sequence[str] = ()
    trunk_head_link_patterns: Sequence[str] = ()
    terminate_on_thigh_contact: bool = True
    ground_force_threshold: float = 50.0
    self_collision_force_threshold: float = 20.0
    reward_term_count: int = 0
    task_param_count: int = 0
    task_flag_count: int = 0
    actor_obs_dim: int = 0
    critic_obs_dim: int = 0

class NativeLocomotionBatchBackend:
    is_fast: bool
    runtime: BatchSimulationRuntime
    spec: LocomotionBatchSpec
    def __init__(
        self,
        runtime: BatchSimulationRuntime,
        *,
        spec: LocomotionBatchSpec | None = None,
        foot_link_names: Sequence[str] = (),
        foot_height_sensor_names: Sequence[str] = (),
        foot_contact_sensor_names: Sequence[str] = (),
        height_scan_sensor: str | None = None,
        thigh_link_patterns: Sequence[str] = (),
        shank_link_patterns: Sequence[str] = (),
        trunk_head_link_patterns: Sequence[str] = (),
        terminate_on_thigh_contact: bool = True,
        ground_force_threshold: float = 50.0,
        self_collision_force_threshold: float = 20.0,
        reward_term_count: int = 0,
        task_param_count: int = 0,
        task_flag_count: int = 0,
        actor_obs_dim: int = 0,
        critic_obs_dim: int = 0,
    ) -> None: ...
    @property
    def env_count(self) -> int: ...
    @property
    def state(self) -> Any: ...
    def configure(self, num_envs: int) -> None: ...
    def resolved_workers(self, workers: int = 0) -> int: ...
    def step(self, ctrl: Any, nsteps: int, *, workers: int = 0) -> dict[str, Any]: ...
    def step_actions(self, actions: Any, nsteps: int, *, workers: int = 0, simulate_action_latency: bool = False) -> dict[str, Any]: ...
    def configure_command(self, **kwargs: Any) -> None: ...
    def set_command_ranges(self, *, lin_vel_x: Sequence[float], lin_vel_y: Sequence[float], ang_vel_z: Sequence[float]) -> None: ...
    def reset_commands(self, env_ids: Sequence[int]) -> None: ...
    def step_task_inputs(self, actions: Any, nsteps: int, *, workers: int = 0, simulate_action_latency: bool = False) -> dict[str, Any]: ...
    def step_profile(self) -> dict[str, float]: ...
    def set_position_targets(self, ctrl: Any) -> None: ...
    def set_joint_position_target(self, env_id: int, joint: str, target_position: float) -> None: ...
    def reset_env(self, env_id: int) -> None: ...
    def reset_joint_state(self, env_id: int, joint: str, position: float, velocity: float = 0.0) -> None: ...
    def reset_link_state(
        self,
        env_id: int,
        link: str,
        position: Sequence[float],
        orientation: Sequence[float] = (1.0, 0.0, 0.0, 0.0),
        linear_velocity: Sequence[float] = (0.0, 0.0, 0.0),
        angular_velocity: Sequence[float] = (0.0, 0.0, 0.0),
    ) -> None: ...
    def reset_robot_states(self, env_ids: Sequence[int], **kwargs: Any) -> None: ...
    def set_base_velocity(self, env_id: int, linear_velocity: Any, angular_velocity: Any) -> None: ...
    def set_base_velocities(self, env_ids: Sequence[int], linear_velocities: Any, angular_velocities: Any) -> None: ...
    def env_state(self, env_id: int) -> Any: ...
    def refresh(self) -> Any: ...
    def get_base_pos(self) -> np.ndarray: ...
    def get_base_quat(self) -> np.ndarray: ...
    def get_base_lin_vel(self) -> np.ndarray: ...
    def get_base_ang_vel(self) -> np.ndarray: ...
    def get_dof_pos(self) -> np.ndarray: ...
    def get_dof_vel(self) -> np.ndarray: ...
    def get_link_pos(self) -> np.ndarray: ...
    def get_sensor_data(self, name: str) -> np.ndarray: ...
