from __future__ import annotations

from typing import Any, Mapping, Sequence

import numpy as np
import numpy.typing as npt

class SpecField:
    name: str
    dim: int
    units: str
    def __init__(self, name: str, dim: int, units: str = "") -> None: ...

class ObservationSpec:
    version: str
    fields: tuple[SpecField, ...]
    dtype: np.dtype[Any]
    def __init__(self, version: str, fields: tuple[SpecField, ...], dtype: Any = np.float32) -> None: ...
    @property
    def dim(self) -> int: ...
    @property
    def names(self) -> tuple[str, ...]: ...
    def metadata(self) -> dict[str, Any]: ...
    def validate_array(self, values: Any, *, axis: int = -1, name: str = "observation") -> npt.NDArray[np.float32]: ...

class ActionSpec:
    version: str
    fields: tuple[SpecField, ...]
    lower: npt.NDArray[np.float32]
    upper: npt.NDArray[np.float32]
    dtype: np.dtype[Any]
    def __init__(self, version: str, fields: tuple[SpecField, ...], lower: float | Sequence[float] = -1.0, upper: float | Sequence[float] = 1.0, dtype: Any = np.float32) -> None: ...
    @property
    def dim(self) -> int: ...
    @property
    def names(self) -> tuple[str, ...]: ...
    def metadata(self) -> dict[str, Any]: ...
    def validate_array(self, values: Any, *, axis: int = -1, name: str = "action") -> npt.NDArray[np.float32]: ...
    def clip(self, values: Any) -> npt.NDArray[np.float32]: ...

def validate_spec_metadata(metadata: Mapping[str, Any], spec: ObservationSpec | ActionSpec, *, kind: str) -> None: ...
