from __future__ import annotations

import ast
from typing import Any, Callable

class TaskKernelCompileError(RuntimeError): ...

class TaskKernel:
    func: Callable[..., Any]
    source: str
    lineno: int
    tree: ast.Module
    launch: str
    launch_axis: int
    @property
    def name(self) -> str: ...
    @property
    def cache_key_source(self) -> str: ...

def task_kernel(
    func: Callable[..., Any] | None = None,
    *,
    launch: str = "actor_obs",
    launch_axis: int = 0,
) -> TaskKernel | Callable[[Callable[..., Any]], TaskKernel]: ...
kernel = task_kernel
def tid() -> int: ...
def dim(array: Any, axis: int) -> int: ...
def where(condition: bool, true_value: Any, false_value: Any) -> Any: ...
def param(values: Any, index: int, fallback: float) -> float: ...
def flag(values: Any, index: int) -> float: ...
def weight(values: Any, index: int) -> float: ...
def generate_cpp_from_task_kernel(kernel: TaskKernel, arrays: Any, *, abi_version: int) -> tuple[str, tuple[str, ...]]: ...
