"""Runtime profile shared by the conveyor package demo entry points."""

from __future__ import annotations

from dataclasses import dataclass
import math
import os


FIXED_DT = 0.002
BELT_SPEED = 1.0
DEFORMABLE_CONTACT_FRICTION = 0.85
# Exact shell/core masses generated by build_scene.py. Each visible film carries
# most of its parcel inertia; the light hidden body supports volume without
# becoming a separately controlled object.
SOFT_PACKAGE_MASSES = (
    0.30,
    0.05,
    0.14,
    0.025,
)
SOFT_PACKAGE_DAMPING_RATES = (7.0, 7.0, 6.0, 6.0)
DROP_SETTLE_TICKS = 300
FLIP_APPROACH_TICKS = 260
FLIP_CONTACT_TICKS = 180
FLIP_GRIP_TICKS = 220
FLIP_STABILIZE_TICKS = 260
FLIP_ROTATE_TICKS = 480
FLIP_PLACE_TICKS = 260
FLIP_TURNOVER_TICKS = 360
FLIP_RELEASE_TICKS = 180
FLIP_CLEAR_TICKS = 120
FLIP_SETTLE_TICKS = 400
REORIENT_TICKS = 180
PUSH_APPROACH_TICKS = 160
# A 1.04 s sweep keeps the Cartesian wrists below roughly 1.8 m/s at peak.
# The previous 0.56 s sweep made dense shell/fingertip contact branch-sensitive
# and could exhaust the nonlinear safety cap.
PUSH_TICKS = 520
PUSH_RELEASE_TICKS = 80
PUSH_CLEAR_TICKS = 120
YELLOW_FLIP_DEPART_TICKS = 140
YELLOW_FLIP_TRANSFER_TICKS = 220
YELLOW_FLIP_APPROACH_TICKS = 260
YELLOW_FLIP_CONTACT_TICKS = 180
YELLOW_FLIP_GRIP_TICKS = 220
YELLOW_FLIP_STABILIZE_TICKS = 180
YELLOW_FLIP_ROTATE_TICKS = 480
YELLOW_FLIP_PLACE_TICKS = 180
YELLOW_FLIP_RELEASE_TICKS = 180
YELLOW_FLIP_CLEAR_TICKS = 120
YELLOW_FLIP_SETTLE_TICKS = 400
CARTON_FLIP_DEPART_TICKS = 180
# Both soft-package turns leave the wrists at the same side-facing orientation,
# so this high transfer changes position without an unnecessary full revolution.
CARTON_FLIP_TRANSFER_TICKS = 360
CARTON_FLIP_APPROACH_TICKS = 260
CARTON_FLIP_GRIP_TICKS = 140
CARTON_FLIP_STABILIZE_TICKS = 60
CARTON_FLIP_LIFT_TICKS = 80
CARTON_FLIP_ROTATE_TICKS = 420
CARTON_FLIP_PLACE_TICKS = 160
CARTON_FLIP_RELEASE_TICKS = 160
CARTON_FLIP_CLEAR_TICKS = 80
CARTON_FLIP_RAISE_TICKS = 220
RETURN_HOME_TICKS = 220

# Each target is (x, y, z, roll, pitch, yaw) for the invisible Cartesian wrist
# in meters/radians. During a flip the palms face one another across the
# parcel's short sides. The regular fingers form vertical rows beside the
# parcel; keeping the wrist roll at zero here leaves every LEAP visual and
# collision geometry above the table. The wrist x targets provide the grasp
# preload; no deformable vertex is attached to or repositioned by the
# controller.
HAND_STAGE_HOME_TARGETS = (
    (0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
)
HAND_STAGE_FLIP_APPROACH_TARGETS = (
    # The CAD hands are asymmetric. Independent Y/Z offsets align their three
    # regular fingertips and retain at least 10 mm of table clearance after
    # the package-specific blue-hand bias is applied.
    (-0.150, 0.026892, -0.4450, 0.0, -1.5707963267948966, 0.0),
    (0.180, 0.028808, -0.3911, 0.0, 1.5707963267948966, 0.0),
)
HAND_STAGE_FLIP_GRIP_TARGETS = (
    # Move the opposing palm envelopes 50 mm per side to nominal shell
    # contact. Package-specific targets add their measured preload below.
    (-0.100, 0.026892, -0.4450, 0.0, -1.5707963267948966, 0.0),
    (0.130, 0.028808, -0.3911, 0.0, 1.5707963267948966, 0.0),
)
HAND_STAGE_FLIP_STABILIZE_TARGETS = HAND_STAGE_FLIP_GRIP_TARGETS
# This is deliberately a stationary pre-tip hold: gravity and the worktable
# support the parcel while the two palm envelopes maintain side preload.
HAND_STAGE_FLIP_LIFT_TARGETS = HAND_STAGE_FLIP_STABILIZE_TARGETS
HAND_STAGE_FLIPPED_LIFT_TARGETS = (
    # A 90-degree forward wrist tip is sufficient to carry the package beyond
    # its balance point; gravity completes the turnover after release. The
    # remaining wrist rotation is performed during the high transfer, never
    # next to the table.
    (-0.100, 0.026892, -0.3650, -1.5707963267948966, -1.5707963267948966, 0.0),
    (0.130, 0.028808, -0.3111, -1.5707963267948966, 1.5707963267948966, 0.0),
)
HAND_STAGE_FLIP_PLACE_TARGETS = (
    (-0.100, 0.026892, -0.3650, -1.5707963267948966, -1.5707963267948966, 0.0),
    (0.130, 0.028808, -0.3111, -1.5707963267948966, 1.5707963267948966, 0.0),
)
HAND_STAGE_FLIP_RELEASE_TARGETS = HAND_STAGE_FLIP_PLACE_TARGETS
HAND_STAGE_FLIP_CLEAR_TARGETS = (
    (-0.30, 0.056892, -0.2150, -1.5707963267948966, -1.5707963267948966, 0.0),
    (0.32, 0.058808, -0.1611, -1.5707963267948966, 1.5707963267948966, 0.0),
)
BLUE_POST_FLIP_ROLL = 0.0
HAND_STAGE_REORIENT_TARGETS = (
    (-0.12, -0.04, 0.08, BLUE_POST_FLIP_ROLL, 0.0, 0.0),
    (0.12, -0.11, 0.08, BLUE_POST_FLIP_ROLL, 0.0, 0.0),
)
PUSH_CONTACT_HEIGHT_DROP = 0.060
HAND_STAGE_PUSH_APPROACH_TARGETS = (
    # Begin behind the settled shell. Starting beside its centerline applied a
    # rearward squeeze before the +Y sweep and could move it away from the belt.
    # Keep the fingertip rows close to the settled shell center so the push does
    # not add a large overturning moment.
    (0.0, -0.8000, -0.325 - PUSH_CONTACT_HEIGHT_DROP,
     BLUE_POST_FLIP_ROLL, 0.0, 0.0),
    (0.0, -0.8705, -0.2985 - PUSH_CONTACT_HEIGHT_DROP,
     BLUE_POST_FLIP_ROLL, 0.0, 0.0),
)
HAND_STAGE_PUSH_TARGETS = (
    # Carry the mailer's leading edge at least 60 mm past the belt's near edge
    # so the +X surface velocity takes over before the hands release.
    (0.0, 0.45, -0.325 - PUSH_CONTACT_HEIGHT_DROP,
     BLUE_POST_FLIP_ROLL, 0.0, 0.0),
    (0.0, 0.3795, -0.2985 - PUSH_CONTACT_HEIGHT_DROP,
     BLUE_POST_FLIP_ROLL, 0.0, 0.0),
)
PUSH_RELEASE_RETREAT = 0.150
HAND_STAGE_PUSH_RELEASE_TARGETS = tuple(
    (target[0], target[1] - PUSH_RELEASE_RETREAT, *target[2:])
    for target in HAND_STAGE_PUSH_TARGETS
)
PUSH_CLEAR_LIFT = 0.275
HAND_STAGE_PUSH_CLEAR_TARGETS = tuple(
    (target[0], target[1], target[2] + PUSH_CLEAR_LIFT, *target[3:])
    for target in HAND_STAGE_PUSH_RELEASE_TARGETS
)


def _retarget_flip_targets(
    targets: tuple[tuple[float, ...], ...],
    *,
    x_shift: float,
    y_shift: float,
    z_shift: float,
    width_inset: float,
    roll_offset: float,
) -> tuple[tuple[float, ...], ...]:
    return tuple(
        (
            target[0] + x_shift + (width_inset if index == 0 else -width_inset),
            target[1] + y_shift,
            target[2] + z_shift,
            target[3] + roll_offset,
            target[4],
            target[5],
        )
        for index, target in enumerate(targets)
    )


def _high_transfer_targets(
    targets: tuple[tuple[float, ...], ...],
) -> tuple[tuple[float, ...], ...]:
    """Keep lateral/rotational targeting while moving both wrists high."""
    return tuple(
        (target[0], target[1], 0.15, *target[3:]) for target in targets
    )


def _limit_side_preload(
    targets: tuple[tuple[float, ...], ...],
    approach: tuple[tuple[float, ...], ...],
    preload: float,
) -> tuple[tuple[float, ...], ...]:
    return tuple(
        (
            approach_target[0] + (preload if index == 0 else -preload),
            *target[1:],
        )
        for index, (target, approach_target) in enumerate(
            zip(targets, approach, strict=True)
        )
    )


def _offset_hand_targets(
    targets: tuple[tuple[float, ...], ...],
    offsets: tuple[tuple[float, ...], ...],
) -> tuple[tuple[float, ...], ...]:
    """Apply an independent Cartesian offset to each wrist target."""
    return tuple(
        tuple(
            value + offset
            for value, offset in zip(target, hand_offset, strict=True)
        )
        for target, hand_offset in zip(targets, offsets, strict=True)
    )


def _pinched_edge_turnover_targets(
    starts: tuple[tuple[float, ...], ...],
    *,
    fraction: float,
    forward_travel: float,
    end_lift: float,
    arc_height: float,
) -> tuple[tuple[float, ...], ...]:
    """Carry a pinched edge on a half-ellipse around the supported edge."""
    turnover = 0.5 - 0.5 * math.cos(math.pi * fraction)
    lift = end_lift * turnover + arc_height * math.sin(math.pi * fraction)
    return tuple(
        (
            start[0],
            start[1] + forward_travel * turnover,
            start[2] + lift,
            start[3],
            start[4],
            start[5],
        )
        for start in starts
    )


def _table_pivot_turnover_targets(
    starts: tuple[tuple[float, ...], ...],
    *,
    fraction: float,
    forward_travel: float,
    drop: float,
) -> tuple[tuple[float, ...], ...]:
    """Follow a quarter ellipse around a table-supported package edge."""
    angle = 0.5 * math.pi * max(0.0, min(1.0, float(fraction)))
    forward = forward_travel * math.sin(angle)
    downward = drop * (1.0 - math.cos(angle))
    return tuple(
        (
            start[0],
            start[1] + forward,
            start[2] - downward,
            start[3],
            start[4],
            start[5],
        )
        for start in starts
    )


# With zero wrist rotation the authored LEAP alignment puts both palms down.
# These translations place two thumb-middle gaps across the blue mailer's rear
# seam. The approach is a vertical descent; the wrists do not squeeze inward.
SOFT_FLIP_APPROACH_CLEARANCE = 0.160
BLUE_FLIP_PINCH_WORLD_CENTERS = (
    (0.070, -0.525, 0.615),
    (0.250, -0.525, 0.615),
)
HAND_STAGE_BLUE_FLIP_CONTACT_TARGETS = (
    (0.034791550, -0.511852350, -0.293509530, 0.0, 0.0, 0.0),
    (-0.127308430, -0.511967060, -0.294169620, 0.0, 0.0, 0.0),
)
HAND_STAGE_BLUE_FLIP_APPROACH_TARGETS = _offset_hand_targets(
    HAND_STAGE_BLUE_FLIP_CONTACT_TARGETS,
    (
        (0.0, 0.0, SOFT_FLIP_APPROACH_CLEARANCE, 0.0, 0.0, 0.0),
        (0.0, 0.0, SOFT_FLIP_APPROACH_CLEARANCE, 0.0, 0.0, 0.0),
    ),
)
# The fingers provide the grasp; a palm preload would turn this back into the
# side squeeze that the downward pinch is intended to replace.
BLUE_FLIP_PALM_PRELOAD = 0.0
HAND_STAGE_BLUE_FLIP_GRIP_TARGETS = HAND_STAGE_BLUE_FLIP_CONTACT_TARGETS
# Raise the pinched seam by more than the mailer's 320 mm length before the
# horizontal transfer. The free edge therefore clears the table instead of
# being dragged around it while only the wrists appear to move.
BLUE_FLIP_STABILIZE_LIFT = 0.340
HAND_STAGE_BLUE_FLIP_STABILIZE_TARGETS = _offset_hand_targets(
    HAND_STAGE_BLUE_FLIP_GRIP_TARGETS,
    (
        (0.0, 0.0, BLUE_FLIP_STABILIZE_LIFT, 0.0, 0.0, 0.0),
        (0.0, 0.0, BLUE_FLIP_STABILIZE_LIFT, 0.0, 0.0, 0.0),
    ),
)
# Keep both wrists palm-down while the fingers carry the hanging mailer through
# free space. A shallow arc provides acceleration clearance, while the elevated
# start and end points make this a real pick-and-carry rather than a table roll.
# The common translation preserves the bilateral pinch; only contact and film
# deformation can turn the parcel.
BLUE_FLIP_EDGE_FORWARD_TRAVEL = 0.450
BLUE_FLIP_EDGE_END_LIFT = 0.0
BLUE_FLIP_EDGE_ARC_HEIGHT = 0.040
HAND_STAGE_BLUE_FLIPPED_TARGETS = _pinched_edge_turnover_targets(
    HAND_STAGE_BLUE_FLIP_STABILIZE_TARGETS,
    fraction=1.0,
    forward_travel=BLUE_FLIP_EDGE_FORWARD_TRAVEL,
    end_lift=BLUE_FLIP_EDGE_END_LIFT,
    arc_height=BLUE_FLIP_EDGE_ARC_HEIGHT,
)
# Lower only until the hanging film's free edge reaches the table. Advancing
# farther vertically would crush the upright mailer before turnover begins.
BLUE_FLIP_PLACE_DROP = 0.090
HAND_STAGE_BLUE_FLIP_PLACE_TARGETS = tuple(
    (
        target[0],
        target[1],
        target[2] - BLUE_FLIP_PLACE_DROP,
        *target[3:],
    )
    for target in HAND_STAGE_BLUE_FLIPPED_TARGETS
)
BLUE_FLIP_TURNOVER_FORWARD_TRAVEL = 0.450
BLUE_FLIP_TURNOVER_DROP = 0.250
HAND_STAGE_BLUE_FLIP_TURNOVER_TARGETS = _table_pivot_turnover_targets(
    HAND_STAGE_BLUE_FLIP_PLACE_TARGETS,
    fraction=1.0,
    forward_travel=BLUE_FLIP_TURNOVER_FORWARD_TRAVEL,
    drop=BLUE_FLIP_TURNOVER_DROP,
)
HAND_STAGE_BLUE_FLIP_RELEASE_TARGETS = HAND_STAGE_BLUE_FLIP_TURNOVER_TARGETS
BLUE_FLIP_CLEAR_LIFT = 0.180
BLUE_FLIP_CLEAR_SIDE_RETREAT = 0.200
HAND_STAGE_BLUE_FLIP_CLEAR_TARGETS = _offset_hand_targets(
    HAND_STAGE_BLUE_FLIP_RELEASE_TARGETS,
    (
        (-BLUE_FLIP_CLEAR_SIDE_RETREAT, 0.0, BLUE_FLIP_CLEAR_LIFT,
         0.0, 0.0, 0.0),
        (BLUE_FLIP_CLEAR_SIDE_RETREAT, 0.0, BLUE_FLIP_CLEAR_LIFT,
         0.0, 0.0, 0.0),
    ),
)

YELLOW_FLIP_PINCH_WORLD_CENTERS = (
    (-0.505, -0.045, 0.610),
    (-0.335, -0.045, 0.610),
)
HAND_STAGE_YELLOW_FLIP_CONTACT_TARGETS = (
    (-0.540208, -0.009858, -0.285112, 0.0, 0.0, 0.0),
    (-0.712308, -0.009477, -0.285198, 0.0, 0.0, 0.0),
)
HAND_STAGE_YELLOW_FLIP_APPROACH_TARGETS = _offset_hand_targets(
    HAND_STAGE_YELLOW_FLIP_CONTACT_TARGETS,
    (
        (0.0, 0.0, SOFT_FLIP_APPROACH_CLEARANCE, 0.0, 0.0, 0.0),
        (0.0, 0.0, SOFT_FLIP_APPROACH_CLEARANCE, 0.0, 0.0, 0.0),
    ),
)
HAND_STAGE_YELLOW_FLIP_TRANSFER_TARGETS = _high_transfer_targets(
    HAND_STAGE_YELLOW_FLIP_APPROACH_TARGETS
)
HAND_STAGE_BLUE_PUSH_DEPART_TARGETS = _high_transfer_targets(
    HAND_STAGE_PUSH_CLEAR_TARGETS
)
YELLOW_FLIP_PALM_PRELOAD = 0.0
HAND_STAGE_YELLOW_FLIP_GRIP_TARGETS = HAND_STAGE_YELLOW_FLIP_CONTACT_TARGETS
YELLOW_FLIP_STABILIZE_LIFT = 0.030
HAND_STAGE_YELLOW_FLIP_STABILIZE_TARGETS = _offset_hand_targets(
    HAND_STAGE_YELLOW_FLIP_GRIP_TARGETS,
    (
        (0.0, 0.0, YELLOW_FLIP_STABILIZE_LIFT, 0.0, 0.0, 0.0),
        (0.0, 0.0, YELLOW_FLIP_STABILIZE_LIFT, 0.0, 0.0, 0.0),
    ),
)
YELLOW_FLIP_EDGE_FORWARD_TRAVEL = 0.400
YELLOW_FLIP_EDGE_END_LIFT = 0.010
YELLOW_FLIP_EDGE_ARC_HEIGHT = 0.175
HAND_STAGE_YELLOW_FLIPPED_TARGETS = _pinched_edge_turnover_targets(
    HAND_STAGE_YELLOW_FLIP_STABILIZE_TARGETS,
    fraction=1.0,
    forward_travel=YELLOW_FLIP_EDGE_FORWARD_TRAVEL,
    end_lift=YELLOW_FLIP_EDGE_END_LIFT,
    arc_height=YELLOW_FLIP_EDGE_ARC_HEIGHT,
)
YELLOW_FLIP_PLACE_DROP = 0.040
HAND_STAGE_YELLOW_FLIP_PLACE_TARGETS = tuple(
    (
        target[0],
        target[1],
        target[2] - YELLOW_FLIP_PLACE_DROP,
        *target[3:],
    )
    for target in HAND_STAGE_YELLOW_FLIPPED_TARGETS
)
HAND_STAGE_YELLOW_FLIP_RELEASE_TARGETS = HAND_STAGE_YELLOW_FLIP_PLACE_TARGETS
YELLOW_FLIP_CLEAR_LIFT = 0.180
HAND_STAGE_YELLOW_FLIP_CLEAR_TARGETS = _offset_hand_targets(
    HAND_STAGE_YELLOW_FLIP_RELEASE_TARGETS,
    (
        (0.0, 0.0, YELLOW_FLIP_CLEAR_LIFT, 0.0, 0.0, 0.0),
        (0.0, 0.0, YELLOW_FLIP_CLEAR_LIFT, 0.0, 0.0, 0.0),
    ),
)

CARTON_FLIP_X_SHIFT = -1.18
CARTON_FLIP_Y_SHIFT = -0.030
CARTON_FLIP_Z_SHIFT = 0.035
CARTON_FLIP_ROLL_OFFSET = 0.0
CARTON_FLIP_WIDTH_INSET = 0.095
HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS = _retarget_flip_targets(
    HAND_STAGE_FLIP_APPROACH_TARGETS,
    x_shift=CARTON_FLIP_X_SHIFT,
    y_shift=CARTON_FLIP_Y_SHIFT,
    z_shift=CARTON_FLIP_Z_SHIFT,
    width_inset=CARTON_FLIP_WIDTH_INSET,
    roll_offset=CARTON_FLIP_ROLL_OFFSET,
)
HAND_STAGE_CARTON_FLIP_TRANSFER_TARGETS = _high_transfer_targets(
    HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS
)
HAND_STAGE_YELLOW_FLIP_DEPART_TARGETS = _high_transfer_targets(
    HAND_STAGE_YELLOW_FLIP_CLEAR_TARGETS
)
CARTON_FLIP_PALM_PRELOAD = 0.002
HAND_STAGE_CARTON_FLIP_GRIP_TARGETS = _limit_side_preload(
    _retarget_flip_targets(
        HAND_STAGE_FLIP_GRIP_TARGETS,
        x_shift=CARTON_FLIP_X_SHIFT,
        y_shift=CARTON_FLIP_Y_SHIFT,
        z_shift=CARTON_FLIP_Z_SHIFT,
        width_inset=CARTON_FLIP_WIDTH_INSET,
        roll_offset=CARTON_FLIP_ROLL_OFFSET,
    ),
    HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS,
    CARTON_FLIP_PALM_PRELOAD,
)
HAND_STAGE_CARTON_FLIP_STABILIZE_TARGETS = _limit_side_preload(
    _retarget_flip_targets(
        HAND_STAGE_FLIP_STABILIZE_TARGETS,
        x_shift=CARTON_FLIP_X_SHIFT,
        y_shift=CARTON_FLIP_Y_SHIFT,
        z_shift=CARTON_FLIP_Z_SHIFT,
        width_inset=CARTON_FLIP_WIDTH_INSET,
        roll_offset=CARTON_FLIP_ROLL_OFFSET,
    ),
    HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS,
    CARTON_FLIP_PALM_PRELOAD,
)
HAND_STAGE_CARTON_FLIP_LIFT_TARGETS = _limit_side_preload(
    _retarget_flip_targets(
        HAND_STAGE_FLIP_LIFT_TARGETS,
        x_shift=CARTON_FLIP_X_SHIFT,
        y_shift=CARTON_FLIP_Y_SHIFT,
        z_shift=CARTON_FLIP_Z_SHIFT,
        width_inset=CARTON_FLIP_WIDTH_INSET,
        roll_offset=CARTON_FLIP_ROLL_OFFSET,
    ),
    HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS,
    CARTON_FLIP_PALM_PRELOAD,
)
HAND_STAGE_CARTON_FLIPPED_LIFT_TARGETS = _limit_side_preload(
    _retarget_flip_targets(
        HAND_STAGE_FLIPPED_LIFT_TARGETS,
        x_shift=CARTON_FLIP_X_SHIFT,
        y_shift=CARTON_FLIP_Y_SHIFT,
        z_shift=CARTON_FLIP_Z_SHIFT,
        width_inset=CARTON_FLIP_WIDTH_INSET,
        roll_offset=CARTON_FLIP_ROLL_OFFSET,
    ),
    HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS,
    CARTON_FLIP_PALM_PRELOAD,
)
CARTON_FLIP_FOLLOW_THROUGH = 0.140
HAND_STAGE_CARTON_FLIPPED_LIFT_TARGETS = _offset_hand_targets(
    HAND_STAGE_CARTON_FLIPPED_LIFT_TARGETS,
    (
        (0.0, CARTON_FLIP_FOLLOW_THROUGH, 0.0, 0.0, 0.0, 0.0),
        (0.0, CARTON_FLIP_FOLLOW_THROUGH, 0.0, 0.0, 0.0, 0.0),
    ),
)
CARTON_FLIP_PLACE_DROP = 0.080
HAND_STAGE_CARTON_FLIP_PLACE_TARGETS = tuple(
    (
        target[0],
        target[1],
        target[2] - CARTON_FLIP_PLACE_DROP,
        *target[3:],
    )
    for target in HAND_STAGE_CARTON_FLIPPED_LIFT_TARGETS
)
HAND_STAGE_CARTON_FLIP_RELEASE_TARGETS = (
    HAND_STAGE_CARTON_FLIP_PLACE_TARGETS
)
# The left stage is already close to its -1.24 m travel limit at this upstream
# carton. Open the fingers, keep that palm at the limit, and withdraw the right
# palm by 200 mm before either hand rises. This measured sequence leaves the
# inverted carton resting on the table instead of sweeping it upward.
HAND_STAGE_CARTON_FLIP_CLEAR_TARGETS = tuple(
    (
        max(-1.24, target[0] - 0.20)
        if index == 0
        else min(1.24, target[0] + 0.20),
        *target[1:],
    )
    for index, target in enumerate(HAND_STAGE_CARTON_FLIP_RELEASE_TARGETS)
)
HAND_STAGE_CARTON_FLIP_DEPART_TARGETS = _high_transfer_targets(
    HAND_STAGE_CARTON_FLIP_CLEAR_TARGETS
)

HAND_STAGE_RETURN_TARGETS = (
    (0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
)

LEAP_FINGER_CLOSE_TARGETS = (
    1.08, 0.0, 0.82, 0.78,
    1.08, 0.0, 0.82, 0.78,
    1.08, 0.0, 0.82, 0.78,
    0.82, 0.50, 0.82, 0.78,
)
# Finger targets are ordered as index, middle, ring, and thumb. These two
# mirrored poses were fitted against the actual LEAP fingertip collision boxes.
# The ordinary-finger side joints stay at zero, so those fingers remain parallel
# instead of making the diagonal fan seen in the old grasp. The thumb opposes
# the middle fingertip across a 20.5 mm surface gap; the index and ring fingertips
# provide support on either side of that central pinch. This leaves 0.5 mm beyond
# the shell's two 10 mm contact radii instead of authoring penetration into the grip.
LEAP_SOFT_PINCH_TARGETS_BY_SIDE = (
    (
        0.77183991, 0.0, 0.62886172, 0.51236301,
        0.77183991, 0.0, 0.62886172, 0.51236301,
        0.77183991, 0.0, 0.62886172, 0.51236301,
        1.81166641, -0.17158354, 0.63501442, -0.07837034,
    ),
    (
        0.77138685, 0.0, 0.63300671, 0.51594576,
        0.77138685, 0.0, 0.63300671, 0.51594576,
        0.77138685, 0.0, 0.63300671, 0.51594576,
        1.82597524, 0.17633748, 0.62915608, -0.08078635,
    ),
)
# For the airborne blue-mailer carry, all three regular fingertips sit about
# 30 mm below the opposing thumb. This turns the same palm-down pinch into a
# load-bearing grip: gravity seats the film on the regular fingers while the
# thumb supplies normal preload. The 20.5 mm free-space surface gap leaves
# 0.5 mm outside the shell's two 10 mm contact radii, so the pose does not
# author penetration; SuperDex contact and the finger drives produce closure.
LEAP_BLUE_AIR_PINCH_TARGETS_BY_SIDE = (
    (
        0.86142098, 0.0, 0.21113690, 0.52261027,
        0.86142098, 0.0, 0.21113690, 0.52261027,
        0.86142098, 0.0, 0.21113690, 0.52261027,
        1.83725251, -0.17501521, 1.04156902, -0.07993775,
    ),
    (
        0.83774887, 0.0, 0.24554795, 0.52626468,
        0.83774887, 0.0, 0.24554795, 0.52626468,
        0.83774887, 0.0, 0.24554795, 0.52626468,
        1.85544260, 0.17986423, 1.04306922, -0.08240208,
    ),
)
PUSH_FINGER_CLOSE_FRACTION = 0.30
# Both flexible packages use a symmetric seam pinch so neither hand becomes a
# stationary visual pivot while the other hand carries the whole parcel.
BLUE_FLIP_FINGER_CLOSE_FRACTIONS = (1.0, 1.0)
YELLOW_FLIP_FINGER_CLOSE_FRACTIONS = (1.0, 1.0)
# The deeper blue hook needs a wider opening than the flat yellow pinch. At
# 60% closure its thumb-middle surface gap is about 107 mm, enough to unwrap a
# folded film edge before the wrists move. The yellow pose keeps the smaller
# opening that was already validated for its table-supported turn.
BLUE_FLIP_RELEASE_CLOSE_FRACTION = 0.60
SOFT_FLIP_RELEASE_CLOSE_FRACTION = 0.90
CARTON_FLIP_FINGER_CLOSE_FRACTION = 0.15


@dataclass(frozen=True)
class HandMotionSegment:
    phase: str
    duration: int
    start: tuple[tuple[float, ...], ...]
    end: tuple[tuple[float, ...], ...]
    close_start: float | tuple[float, float] = 0.0
    close_end: float | tuple[float, float] = 0.0


HAND_MOTION_SEGMENTS = (
    HandMotionSegment(
        "drop_settle", DROP_SETTLE_TICKS,
        HAND_STAGE_HOME_TARGETS, HAND_STAGE_HOME_TARGETS,
    ),
    HandMotionSegment(
        "blue_flip_approach", FLIP_APPROACH_TICKS,
        HAND_STAGE_HOME_TARGETS, HAND_STAGE_BLUE_FLIP_APPROACH_TARGETS,
    ),
    HandMotionSegment(
        "blue_flip_contact", FLIP_CONTACT_TICKS,
        HAND_STAGE_BLUE_FLIP_APPROACH_TARGETS,
        HAND_STAGE_BLUE_FLIP_CONTACT_TARGETS,
    ),
    HandMotionSegment(
        "blue_flip_grip", FLIP_GRIP_TICKS,
        HAND_STAGE_BLUE_FLIP_CONTACT_TARGETS,
        HAND_STAGE_BLUE_FLIP_GRIP_TARGETS,
        0.0, BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "blue_flip_stabilize", FLIP_STABILIZE_TICKS,
        HAND_STAGE_BLUE_FLIP_GRIP_TARGETS,
        HAND_STAGE_BLUE_FLIP_STABILIZE_TARGETS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "blue_flip_rotate", FLIP_ROTATE_TICKS,
        HAND_STAGE_BLUE_FLIP_STABILIZE_TARGETS,
        HAND_STAGE_BLUE_FLIPPED_TARGETS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "blue_flip_place", FLIP_PLACE_TICKS,
        HAND_STAGE_BLUE_FLIPPED_TARGETS,
        HAND_STAGE_BLUE_FLIP_PLACE_TARGETS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "blue_flip_turnover", FLIP_TURNOVER_TICKS,
        HAND_STAGE_BLUE_FLIP_PLACE_TARGETS,
        HAND_STAGE_BLUE_FLIP_TURNOVER_TARGETS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "blue_flip_release", FLIP_RELEASE_TICKS,
        HAND_STAGE_BLUE_FLIP_TURNOVER_TARGETS,
        HAND_STAGE_BLUE_FLIP_RELEASE_TARGETS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
        BLUE_FLIP_RELEASE_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "blue_flip_clear", FLIP_CLEAR_TICKS,
        HAND_STAGE_BLUE_FLIP_RELEASE_TARGETS,
        HAND_STAGE_BLUE_FLIP_CLEAR_TARGETS,
        BLUE_FLIP_RELEASE_CLOSE_FRACTION,
        BLUE_FLIP_RELEASE_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "blue_flip_settle", FLIP_SETTLE_TICKS,
        HAND_STAGE_BLUE_FLIP_CLEAR_TARGETS,
        HAND_STAGE_BLUE_FLIP_CLEAR_TARGETS,
        BLUE_FLIP_RELEASE_CLOSE_FRACTION, 0.0,
    ),
    HandMotionSegment(
        "blue_reorient", REORIENT_TICKS,
        HAND_STAGE_BLUE_FLIP_CLEAR_TARGETS, HAND_STAGE_REORIENT_TARGETS,
    ),
    HandMotionSegment(
        "blue_push_approach", PUSH_APPROACH_TICKS,
        HAND_STAGE_REORIENT_TARGETS, HAND_STAGE_PUSH_APPROACH_TARGETS,
        0.0, PUSH_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "blue_push", PUSH_TICKS,
        HAND_STAGE_PUSH_APPROACH_TARGETS, HAND_STAGE_PUSH_TARGETS,
        PUSH_FINGER_CLOSE_FRACTION, PUSH_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "blue_push_release", PUSH_RELEASE_TICKS,
        HAND_STAGE_PUSH_TARGETS, HAND_STAGE_PUSH_RELEASE_TARGETS,
        PUSH_FINGER_CLOSE_FRACTION, 0.0,
    ),
    HandMotionSegment(
        "blue_push_clear", PUSH_CLEAR_TICKS,
        HAND_STAGE_PUSH_RELEASE_TARGETS, HAND_STAGE_PUSH_CLEAR_TARGETS,
    ),
    HandMotionSegment(
        "blue_push_depart", YELLOW_FLIP_DEPART_TICKS,
        HAND_STAGE_PUSH_CLEAR_TARGETS, HAND_STAGE_BLUE_PUSH_DEPART_TARGETS,
    ),
    HandMotionSegment(
        "yellow_flip_transfer", YELLOW_FLIP_TRANSFER_TICKS,
        HAND_STAGE_BLUE_PUSH_DEPART_TARGETS,
        HAND_STAGE_YELLOW_FLIP_TRANSFER_TARGETS,
    ),
    HandMotionSegment(
        "yellow_flip_approach", YELLOW_FLIP_APPROACH_TICKS,
        HAND_STAGE_YELLOW_FLIP_TRANSFER_TARGETS,
        HAND_STAGE_YELLOW_FLIP_APPROACH_TARGETS,
    ),
    HandMotionSegment(
        "yellow_flip_contact", YELLOW_FLIP_CONTACT_TICKS,
        HAND_STAGE_YELLOW_FLIP_APPROACH_TARGETS,
        HAND_STAGE_YELLOW_FLIP_CONTACT_TARGETS,
    ),
    HandMotionSegment(
        "yellow_flip_grip", YELLOW_FLIP_GRIP_TICKS,
        HAND_STAGE_YELLOW_FLIP_CONTACT_TARGETS,
        HAND_STAGE_YELLOW_FLIP_GRIP_TARGETS,
        0.0, YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "yellow_flip_stabilize", YELLOW_FLIP_STABILIZE_TICKS,
        HAND_STAGE_YELLOW_FLIP_GRIP_TARGETS,
        HAND_STAGE_YELLOW_FLIP_STABILIZE_TARGETS,
        YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
        YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "yellow_flip_rotate", YELLOW_FLIP_ROTATE_TICKS,
        HAND_STAGE_YELLOW_FLIP_STABILIZE_TARGETS,
        HAND_STAGE_YELLOW_FLIPPED_TARGETS,
        YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
        YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "yellow_flip_place", YELLOW_FLIP_PLACE_TICKS,
        HAND_STAGE_YELLOW_FLIPPED_TARGETS,
        HAND_STAGE_YELLOW_FLIP_PLACE_TARGETS,
        YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
        YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "yellow_flip_release", YELLOW_FLIP_RELEASE_TICKS,
        HAND_STAGE_YELLOW_FLIP_PLACE_TARGETS,
        HAND_STAGE_YELLOW_FLIP_RELEASE_TARGETS,
        YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
        SOFT_FLIP_RELEASE_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "yellow_flip_clear", YELLOW_FLIP_CLEAR_TICKS,
        HAND_STAGE_YELLOW_FLIP_RELEASE_TARGETS,
        HAND_STAGE_YELLOW_FLIP_CLEAR_TARGETS,
        SOFT_FLIP_RELEASE_CLOSE_FRACTION,
        SOFT_FLIP_RELEASE_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "yellow_flip_settle", YELLOW_FLIP_SETTLE_TICKS,
        HAND_STAGE_YELLOW_FLIP_CLEAR_TARGETS,
        HAND_STAGE_YELLOW_FLIP_CLEAR_TARGETS,
        SOFT_FLIP_RELEASE_CLOSE_FRACTION, 0.0,
    ),
    HandMotionSegment(
        "yellow_flip_depart", CARTON_FLIP_DEPART_TICKS,
        HAND_STAGE_YELLOW_FLIP_CLEAR_TARGETS,
        HAND_STAGE_YELLOW_FLIP_DEPART_TARGETS,
    ),
    HandMotionSegment(
        "carton_flip_transfer", CARTON_FLIP_TRANSFER_TICKS,
        HAND_STAGE_YELLOW_FLIP_DEPART_TARGETS,
        HAND_STAGE_CARTON_FLIP_TRANSFER_TARGETS,
    ),
    HandMotionSegment(
        "carton_flip_approach", CARTON_FLIP_APPROACH_TICKS,
        HAND_STAGE_CARTON_FLIP_TRANSFER_TARGETS,
        HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS,
    ),
    HandMotionSegment(
        "carton_flip_grip", CARTON_FLIP_GRIP_TICKS,
        HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS,
        HAND_STAGE_CARTON_FLIP_GRIP_TARGETS,
        0.0, CARTON_FLIP_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "carton_flip_stabilize", CARTON_FLIP_STABILIZE_TICKS,
        HAND_STAGE_CARTON_FLIP_GRIP_TARGETS,
        HAND_STAGE_CARTON_FLIP_STABILIZE_TARGETS,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "carton_flip_lift", CARTON_FLIP_LIFT_TICKS,
        HAND_STAGE_CARTON_FLIP_STABILIZE_TARGETS,
        HAND_STAGE_CARTON_FLIP_LIFT_TARGETS,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "carton_flip_rotate", CARTON_FLIP_ROTATE_TICKS,
        HAND_STAGE_CARTON_FLIP_LIFT_TARGETS,
        HAND_STAGE_CARTON_FLIPPED_LIFT_TARGETS,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "carton_flip_place", CARTON_FLIP_PLACE_TICKS,
        HAND_STAGE_CARTON_FLIPPED_LIFT_TARGETS,
        HAND_STAGE_CARTON_FLIP_PLACE_TARGETS,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "carton_flip_release", CARTON_FLIP_RELEASE_TICKS,
        HAND_STAGE_CARTON_FLIP_PLACE_TARGETS,
        HAND_STAGE_CARTON_FLIP_RELEASE_TARGETS,
        CARTON_FLIP_FINGER_CLOSE_FRACTION, 0.0,
    ),
    HandMotionSegment(
        "carton_flip_clear", CARTON_FLIP_CLEAR_TICKS,
        HAND_STAGE_CARTON_FLIP_RELEASE_TARGETS,
        HAND_STAGE_CARTON_FLIP_CLEAR_TARGETS,
    ),
    HandMotionSegment(
        "carton_flip_depart", CARTON_FLIP_RAISE_TICKS,
        HAND_STAGE_CARTON_FLIP_CLEAR_TARGETS,
        HAND_STAGE_CARTON_FLIP_DEPART_TARGETS,
    ),
    HandMotionSegment(
        "return_home", RETURN_HOME_TICKS,
        HAND_STAGE_CARTON_FLIP_DEPART_TARGETS, HAND_STAGE_RETURN_TARGETS,
    ),
)
MANIPULATION_TICKS = sum(segment.duration for segment in HAND_MOTION_SEGMENTS)
RAMP_TICKS = 80
CONVEY_TICKS = 180
BRAKE_TICKS = 160
HOLD_TICKS = 240
_BLUE_PUSH_SEGMENT_INDEX = next(
    index
    for index, segment in enumerate(HAND_MOTION_SEGMENTS)
    if segment.phase == "blue_push"
)
BELT_START_TICKS = sum(
    segment.duration
    for segment in HAND_MOTION_SEGMENTS[: _BLUE_PUSH_SEGMENT_INDEX + 1]
)
CYCLE_TICKS = max(
    MANIPULATION_TICKS,
    BELT_START_TICKS + RAMP_TICKS + CONVEY_TICKS + BRAKE_TICKS,
) + HOLD_TICKS
# Damping helps a freely carried parcel settle. The blue mailer now crosses the
# balance point geometrically while suspended, so it keeps damping throughout
# the lift and transfer. The original table-supported yellow turn still needs
# its undamped angular momentum.
SOFT_DAMPING_DISABLED_PHASES = frozenset(
    ("yellow_flip_rotate",)
)
QUALITY_ENVIRONMENT_VARIABLE = "GOBOT_CONVEYOR_QUALITY"


@dataclass(frozen=True)
class ConveyorQualityProfile:
    name: str
    contact_refresh_interval: int
    newton_max_iterations: int
    line_search_max_iterations: int


QUALITY_PROFILES = {
    "interactive": ConveyorQualityProfile(
        name="interactive",
        contact_refresh_interval=4,
        newton_max_iterations=16,
        line_search_max_iterations=8,
    ),
    "accurate": ConveyorQualityProfile(
        name="accurate",
        contact_refresh_interval=1,
        # Dense fingertip/shell contact occasionally needs more than the
        # interactive cap; Newton still exits early on ordinary frames.
        newton_max_iterations=48,
        line_search_max_iterations=8,
    ),
}


def quality_profile(name: str | None = None) -> ConveyorQualityProfile:
    selected = (
        name
        if name is not None
        else os.environ.get(QUALITY_ENVIRONMENT_VARIABLE, "interactive")
    )
    selected = str(selected).strip().lower()
    try:
        return QUALITY_PROFILES[selected]
    except KeyError as error:
        choices = ", ".join(repr(value) for value in QUALITY_PROFILES)
        raise ValueError(
            f"{QUALITY_ENVIRONMENT_VARIABLE} must be one of {choices}"
        ) from error


def smoothstep(value: float) -> float:
    value = max(0.0, min(1.0, float(value)))
    return value * value * (3.0 - 2.0 * value)


def belt_speed_at_tick(tick: int) -> float:
    tick = max(0, int(tick))
    if tick < BELT_START_TICKS:
        return 0.0
    tick -= BELT_START_TICKS
    if tick < RAMP_TICKS:
        return BELT_SPEED * smoothstep(float(tick + 1) / RAMP_TICKS)
    tick -= RAMP_TICKS
    if tick < CONVEY_TICKS:
        return BELT_SPEED
    tick -= CONVEY_TICKS
    if tick < BRAKE_TICKS:
        return BELT_SPEED * (
            1.0 - smoothstep(float(tick + 1) / BRAKE_TICKS)
        )
    return 0.0


def _lerp_targets(
    start: tuple[tuple[float, ...], ...],
    end: tuple[tuple[float, ...], ...],
    fraction: float,
) -> tuple[tuple[float, ...], ...]:
    return tuple(
        tuple(
            start_value + (end_value - start_value) * fraction
            for start_value, end_value in zip(
                start_hand, end_hand, strict=True
            )
        )
        for start_hand, end_hand in zip(start, end, strict=True)
    )


def _transition(
    tick: int,
    duration: int,
    start: tuple[tuple[float, ...], ...],
    end: tuple[tuple[float, ...], ...],
) -> tuple[tuple[float, ...], ...]:
    fraction = smoothstep(float(tick + 1) / duration)
    return _lerp_targets(start, end, fraction)


def _motion_segment_at_tick(
    tick: int,
) -> tuple[HandMotionSegment | None, int]:
    local_tick = max(0, int(tick))
    for segment in HAND_MOTION_SEGMENTS:
        if local_tick < segment.duration:
            return segment, local_tick
        local_tick -= segment.duration
    return None, 0


def hand_stage_targets_at_tick(
    tick: int,
) -> tuple[tuple[float, ...], ...]:
    segment, local_tick = _motion_segment_at_tick(tick)
    if segment is None:
        return HAND_MOTION_SEGMENTS[-1].end
    if segment.phase == "blue_flip_rotate":
        fraction = smoothstep(float(local_tick + 1) / segment.duration)
        return _pinched_edge_turnover_targets(
            HAND_STAGE_BLUE_FLIP_STABILIZE_TARGETS,
            fraction=fraction,
            forward_travel=BLUE_FLIP_EDGE_FORWARD_TRAVEL,
            end_lift=BLUE_FLIP_EDGE_END_LIFT,
            arc_height=BLUE_FLIP_EDGE_ARC_HEIGHT,
        )
    if segment.phase == "blue_flip_turnover":
        fraction = smoothstep(float(local_tick + 1) / segment.duration)
        return _table_pivot_turnover_targets(
            HAND_STAGE_BLUE_FLIP_PLACE_TARGETS,
            fraction=fraction,
            forward_travel=BLUE_FLIP_TURNOVER_FORWARD_TRAVEL,
            drop=BLUE_FLIP_TURNOVER_DROP,
        )
    if segment.phase == "yellow_flip_rotate":
        fraction = smoothstep(float(local_tick + 1) / segment.duration)
        return _pinched_edge_turnover_targets(
            HAND_STAGE_YELLOW_FLIP_STABILIZE_TARGETS,
            fraction=fraction,
            forward_travel=YELLOW_FLIP_EDGE_FORWARD_TRAVEL,
            end_lift=YELLOW_FLIP_EDGE_END_LIFT,
            arc_height=YELLOW_FLIP_EDGE_ARC_HEIGHT,
        )
    return _transition(
        local_tick,
        segment.duration,
        segment.start,
        segment.end,
    )


def _finger_close_pair(
    value: float | tuple[float, float],
) -> tuple[float, float]:
    if isinstance(value, tuple):
        if len(value) != 2:
            raise ValueError("finger close target must contain two hands")
        return (float(value[0]), float(value[1]))
    scalar = float(value)
    return (scalar, scalar)


def finger_close_fractions_at_tick(tick: int) -> tuple[float, float]:
    segment, local_tick = _motion_segment_at_tick(tick)
    if segment is None:
        return (0.0, 0.0)
    fraction = smoothstep(float(local_tick + 1) / segment.duration)
    close_start = _finger_close_pair(segment.close_start)
    close_end = _finger_close_pair(segment.close_end)
    return tuple(
        start + (end - start) * fraction
        for start, end in zip(close_start, close_end, strict=True)
    )


def finger_close_fraction_at_tick(tick: int) -> float:
    """Return the strongest hand closure for compact UI diagnostics."""
    return max(finger_close_fractions_at_tick(tick))


def hand_finger_targets_at_tick(
    tick: int,
) -> tuple[tuple[float, ...], ...]:
    segment, _ = _motion_segment_at_tick(tick)
    close_fractions = finger_close_fractions_at_tick(tick)
    blue_air_pinch = segment is not None and segment.phase.startswith(
        "blue_flip_"
    )
    soft_pinch = segment is not None and segment.phase.startswith(
        "yellow_flip_"
    )
    if blue_air_pinch:
        full_targets = LEAP_BLUE_AIR_PINCH_TARGETS_BY_SIDE
    elif soft_pinch:
        full_targets = LEAP_SOFT_PINCH_TARGETS_BY_SIDE
    else:
        full_targets = (LEAP_FINGER_CLOSE_TARGETS,) * 2
    return tuple(
        tuple(value * close_fraction for value in targets)
        for targets, close_fraction in zip(
            full_targets, close_fractions, strict=True
        )
    )


def hand_controls_at_tick(tick: int) -> tuple[tuple[float, ...], ...]:
    stage_targets = hand_stage_targets_at_tick(tick)
    return tuple(
        stage + finger_targets
        for stage, finger_targets in zip(
            stage_targets,
            hand_finger_targets_at_tick(tick),
            strict=True,
        )
    )


def cycle_phase(tick: int) -> str:
    segment, _ = _motion_segment_at_tick(tick)
    return segment.phase if segment is not None else "settle"


def soft_damping_scale_at_tick(tick: int) -> float:
    """Return the deformable velocity-damping multiplier for one step."""
    return 0.0 if cycle_phase(tick) in SOFT_DAMPING_DISABLED_PHASES else 1.0
