"""Runtime profile shared by the conveyor package demo entry points."""

from __future__ import annotations

from dataclasses import dataclass
import os


FIXED_DT = 0.002
BELT_SPEED = 1.0
IPC_CONTACT_FRICTION = 0.55
# The palm moves by roughly 0.7 mm per step at peak speed. A 2 mm activation
# shell leaves enough CCD headroom to push the mailer reliably; 1.2 mm was
# measured to enter an unstable high-wrench pass-through regime.
IPC_CONTACT_ACTIVATION_DISTANCE = 2.0e-3
IPC_CONTACT_RESISTANCE = 1.0e8
# Exact shell/core/package masses generated by build_scene.py. The blue
# mailer's film and hidden contents sum to the original 1.12486 kg parcel.
SOFT_PACKAGE_MASSES = (
    0.10017090362179464,
    1.0246887612843519,
    0.9486760425200044,
)
SOFT_PACKAGE_DAMPING_RATES = (7.0, 7.0, 0.70)
DROP_SETTLE_TICKS = 300
APPROACH_TICKS = 120
GRIP_SETTLE_TICKS = 40
# A slower sweep keeps the one-way rigid palm proxy below the IPC contact shell
# velocity limit and avoids alternating forward/reverse friction impulses.
PUSH_TICKS = 220
RELEASE_TICKS = 60
OPEN_SETTLE_TICKS = 40
ARM_CLEAR_TICKS = 80
ARM_RETRACT_TICKS = 80
ARM_GRIP_TARGETS = (
    (
        0.15218051788629053,
        0.674773509062659,
        -0.3838908450856162,
        -0.2866776384080823,
        0.07404602108029916,
        -0.4046708977789035,
        0.3091280760779591,
    ),
    (
        -0.1521842313759919,
        -0.6747729816488792,
        0.3838950507659552,
        -0.28667769618394556,
        -0.07404601151176729,
        0.40467199848422314,
        -0.30912772778366143,
    ),
)
ARM_PUSH_TARGETS = (
    (
        -0.5515327256304942,
        1.024548824152403,
        -0.3500834414461131,
        -1.5138361563105768,
        0.0577966300453157,
        -0.6036853071749293,
        -0.3889583761128033,
    ),
    (
        0.5515274899740556,
        -1.0245489741777086,
        0.35008858062561,
        -1.5138361444995198,
        -0.057797406016364,
        0.6036869795140871,
        0.3889594347583726,
    ),
)
# This first release waypoint moves each physical palm and heel edge away from
# the parcel before the arm rises. It avoids dragging a high-friction proxy up
# the mailer's rear wall during a single long joint-space interpolation.
ARM_CLEAR_TARGETS = (
    (
        -0.15900586160124153,
        0.9584982213207134,
        -0.7677370305861573,
        -0.31665488504882744,
        -9.945789999999998e-06,
        -0.7098239989999999,
        0.4154449989999999,
    ),
    (
        0.15900035732950588,
        -0.9584979478250945,
        0.76774301269099,
        -0.3166547222772456,
        9.945789999999998e-06,
        0.7098259989999999,
        -0.4154459989999999,
    ),
)
ARM_RETRACT_TARGETS = (
    (
        -0.5032405015119474,
        1.020232776980723,
        -0.8269004208833237,
        -0.8036166983349011,
        -9.945789999999998e-06,
        -0.7098239989999999,
        0.3064371218209275,
    ),
    (
        0.5032352589538494,
        -1.0202319093036945,
        0.8269054152345843,
        -0.8036165288460911,
        9.945789999999998e-06,
        0.7098259989999999,
        -0.3064360216928459,
    ),
)
MANIPULATION_TICKS = (
    DROP_SETTLE_TICKS
    + APPROACH_TICKS
    + GRIP_SETTLE_TICKS
    + PUSH_TICKS
    + RELEASE_TICKS
    + OPEN_SETTLE_TICKS
    + ARM_CLEAR_TICKS
    + ARM_RETRACT_TICKS
)
FINGER_GRIP_OFFSETS = (-0.48, 0.48)
RAMP_TICKS = 80
CONVEY_TICKS = 120
BRAKE_TICKS = 160
HOLD_TICKS = 0
# The outfeed starts when the fingers finish opening. Waiting until the arms are
# fully retracted misses the physical belt-contact window and leaves the parcel
# perched at the table edge.
BELT_START_TICKS = (
    DROP_SETTLE_TICKS
    + APPROACH_TICKS
    + GRIP_SETTLE_TICKS
    + PUSH_TICKS
    + RELEASE_TICKS
)
CYCLE_TICKS = (
    MANIPULATION_TICKS
    + RAMP_TICKS
    + CONVEY_TICKS
    + BRAKE_TICKS
    + HOLD_TICKS
)
QUALITY_ENVIRONMENT_VARIABLE = "GOBOT_CONVEYOR_QUALITY"


@dataclass(frozen=True)
class ConveyorQualityProfile:
    name: str
    coupling_iterations: int
    relaxation_mode: str
    scene_sync_interval: int
    contact_refresh_interval: int
    newton_max_iterations: int
    line_search_max_iterations: int
    linear_system_tolerance_rate: float
    strict_convergence: bool


QUALITY_PROFILES = {
    "interactive": ConveyorQualityProfile(
        name="interactive",
        coupling_iterations=1,
        relaxation_mode="fixed",
        scene_sync_interval=2,
        contact_refresh_interval=4,
        newton_max_iterations=12,
        line_search_max_iterations=6,
        linear_system_tolerance_rate=2.0e-3,
        strict_convergence=False,
    ),
    "accurate": ConveyorQualityProfile(
        name="accurate",
        coupling_iterations=2,
        relaxation_mode="aitken",
        scene_sync_interval=1,
        contact_refresh_interval=1,
        newton_max_iterations=16,
        line_search_max_iterations=8,
        linear_system_tolerance_rate=1.0e-3,
        strict_convergence=True,
    ),
}


def quality_profile(name: str | None = None) -> ConveyorQualityProfile:
    selected = (
        name
        if name is not None
        else os.environ.get(QUALITY_ENVIRONMENT_VARIABLE, "interactive")
    )
    selected = str(selected).strip().lower()
    try:
        return QUALITY_PROFILES[selected]
    except KeyError as error:
        choices = ", ".join(repr(value) for value in QUALITY_PROFILES)
        raise ValueError(
            f"{QUALITY_ENVIRONMENT_VARIABLE} must be one of {choices}"
        ) from error


def smoothstep(value: float) -> float:
    value = max(0.0, min(1.0, float(value)))
    return value * value * (3.0 - 2.0 * value)


def belt_speed_at_tick(tick: int) -> float:
    tick = max(0, int(tick))
    if tick < BELT_START_TICKS:
        return 0.0
    tick -= BELT_START_TICKS
    if tick < RAMP_TICKS:
        return BELT_SPEED * smoothstep(float(tick + 1) / RAMP_TICKS)
    tick -= RAMP_TICKS
    if tick < CONVEY_TICKS:
        return BELT_SPEED
    tick -= CONVEY_TICKS
    if tick < BRAKE_TICKS:
        return BELT_SPEED * (
            1.0 - smoothstep(float(tick + 1) / BRAKE_TICKS)
        )
    return 0.0


def gripper_close_fraction_at_tick(tick: int) -> float:
    tick = max(0, int(tick))
    if tick < DROP_SETTLE_TICKS:
        return 0.0
    tick -= DROP_SETTLE_TICKS
    if tick < APPROACH_TICKS:
        return smoothstep(float(tick + 1) / APPROACH_TICKS)
    tick -= APPROACH_TICKS
    if tick < GRIP_SETTLE_TICKS + PUSH_TICKS:
        return 1.0
    tick -= GRIP_SETTLE_TICKS + PUSH_TICKS
    if tick < RELEASE_TICKS:
        return 1.0 - smoothstep(float(tick + 1) / RELEASE_TICKS)
    return 0.0


def arm_grip_fraction_at_tick(tick: int) -> float:
    tick = max(0, int(tick))
    if tick < DROP_SETTLE_TICKS:
        return 0.0
    tick -= DROP_SETTLE_TICKS
    if tick < APPROACH_TICKS:
        return smoothstep(float(tick + 1) / APPROACH_TICKS)
    return 1.0


def arm_push_fraction_at_tick(tick: int) -> float:
    tick = max(0, int(tick))
    if tick < DROP_SETTLE_TICKS:
        return 0.0
    tick -= DROP_SETTLE_TICKS
    push_start = APPROACH_TICKS + GRIP_SETTLE_TICKS
    if tick < push_start:
        return 0.0
    tick -= push_start
    if tick < PUSH_TICKS:
        return smoothstep(float(tick + 1) / PUSH_TICKS)
    return 1.0


def arm_clear_fraction_at_tick(tick: int) -> float:
    tick = max(0, int(tick))
    if tick < DROP_SETTLE_TICKS:
        return 0.0
    tick -= DROP_SETTLE_TICKS
    clear_start = (
        APPROACH_TICKS
        + GRIP_SETTLE_TICKS
        + PUSH_TICKS
        + RELEASE_TICKS
        + OPEN_SETTLE_TICKS
    )
    if tick < clear_start:
        return 0.0
    tick -= clear_start
    return smoothstep(float(tick + 1) / ARM_CLEAR_TICKS)


def arm_retract_fraction_at_tick(tick: int) -> float:
    tick = max(0, int(tick))
    if tick < DROP_SETTLE_TICKS:
        return 0.0
    tick -= DROP_SETTLE_TICKS
    retract_start = (
        APPROACH_TICKS
        + GRIP_SETTLE_TICKS
        + PUSH_TICKS
        + RELEASE_TICKS
        + OPEN_SETTLE_TICKS
        + ARM_CLEAR_TICKS
    )
    if tick < retract_start:
        return 0.0
    tick -= retract_start
    return smoothstep(float(tick + 1) / ARM_RETRACT_TICKS)


def cycle_phase(tick: int) -> str:
    tick = max(0, int(tick))
    if tick < DROP_SETTLE_TICKS:
        return "drop_settle"
    tick -= DROP_SETTLE_TICKS
    if tick < APPROACH_TICKS:
        return "approach"
    tick -= APPROACH_TICKS
    if tick < GRIP_SETTLE_TICKS:
        return "grip"
    tick -= GRIP_SETTLE_TICKS
    if tick < PUSH_TICKS:
        return "push"
    tick -= PUSH_TICKS
    if tick < RELEASE_TICKS:
        return "release"
    tick -= RELEASE_TICKS
    if tick < OPEN_SETTLE_TICKS:
        return "open_settle"
    tick -= OPEN_SETTLE_TICKS
    if tick < ARM_CLEAR_TICKS:
        return "clear"
    tick -= ARM_CLEAR_TICKS
    if tick < ARM_RETRACT_TICKS:
        return "retract"
    return "settle"
