"""Runtime profile shared by the conveyor package demo entry points."""

from __future__ import annotations

from dataclasses import dataclass
import math
import os


FIXED_DT = 0.002
BELT_SPEED = 1.0
# libuipc multiplies this material scale by the geometric mean of each pair's
# authored coefficients. The LEAP fingertips intentionally use more friction
# than the laminate table so a light film seam remains held during wrist roll.
IPC_CONTACT_FRICTION = 0.85
# The palm moves by roughly 0.7 mm per step at peak speed. A 2 mm activation
# shell leaves enough CCD headroom to push the mailer reliably; 1.2 mm was
# measured to enter an unstable high-wrench pass-through regime.
IPC_CONTACT_ACTIVATION_DISTANCE = 2.0e-3
IPC_CONTACT_RESISTANCE = 1.0e8
# Exact shell/core masses generated by build_scene.py. Each visible film carries
# most of its parcel inertia; the light hidden body supports volume without
# becoming a separately controlled object.
SOFT_PACKAGE_MASSES = (
    0.30,
    0.05,
    0.24,
    0.04,
)
SOFT_PACKAGE_DAMPING_RATES = (7.0, 7.0, 6.0, 6.0)
DROP_SETTLE_TICKS = 300
FLIP_APPROACH_TICKS = 260
FLIP_CONTACT_TICKS = 180
FLIP_GRIP_TICKS = 220
FLIP_STABILIZE_TICKS = 40
FLIP_ROTATE_TICKS = 480
FLIP_RELEASE_TICKS = 120
FLIP_CLEAR_TICKS = 120
FLIP_SETTLE_TICKS = 300
REORIENT_TICKS = 180
PUSH_APPROACH_TICKS = 160
# A 0.8 s sweep keeps the Cartesian wrists below roughly 1.1 m/s at peak.
# The previous 0.56 s sweep made dense shell/fingertip contact branch-sensitive
# and could exhaust the nonlinear safety cap.
PUSH_TICKS = 400
PUSH_RELEASE_TICKS = 80
PUSH_CLEAR_TICKS = 120
YELLOW_FLIP_DEPART_TICKS = 140
YELLOW_FLIP_TRANSFER_TICKS = 220
YELLOW_FLIP_APPROACH_TICKS = 260
YELLOW_FLIP_CONTACT_TICKS = 180
YELLOW_FLIP_GRIP_TICKS = 220
YELLOW_FLIP_STABILIZE_TICKS = 40
YELLOW_FLIP_ROTATE_TICKS = 480
YELLOW_FLIP_RELEASE_TICKS = 120
YELLOW_FLIP_CLEAR_TICKS = 120
YELLOW_FLIP_SETTLE_TICKS = 300
CARTON_FLIP_DEPART_TICKS = 180
# Both soft-package turns leave the wrists at the same side-facing orientation,
# so this high transfer changes position without an unnecessary full revolution.
CARTON_FLIP_TRANSFER_TICKS = 360
CARTON_FLIP_APPROACH_TICKS = 260
CARTON_FLIP_GRIP_TICKS = 140
CARTON_FLIP_STABILIZE_TICKS = 60
CARTON_FLIP_LIFT_TICKS = 80
CARTON_FLIP_ROTATE_TICKS = 420
CARTON_FLIP_PLACE_TICKS = 160
CARTON_FLIP_RELEASE_TICKS = 160
CARTON_FLIP_CLEAR_TICKS = 80
CARTON_FLIP_RAISE_TICKS = 220
RETURN_HOME_TICKS = 220

# Each target is (x, y, z, roll, pitch, yaw) for the invisible Cartesian wrist
# in meters/radians. During the flip the palms face one another across the
# mailer's short sides. The wrist x targets provide the grasp preload; no
# deformable vertex is attached to or repositioned by the controller.
HAND_STAGE_HOME_TARGETS = (
    (0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
)
HAND_STAGE_FLIP_APPROACH_TARGETS = (
    # Rolling the side-facing palms by -90 degrees puts the three regular
    # fingertips in one horizontal row. At 70% closure they sweep inward and
    # upward from just above the table, so the grip has geometric support
    # instead of relying on side friction from one low finger.
    (-0.150, -0.053108, -0.4800, -1.5707963267948966, -1.5707963267948966, 0.0),
    (0.180, 0.114808, -0.4311, -1.5707963267948966, 1.5707963267948966, 0.0),
)
HAND_STAGE_FLIP_GRIP_TARGETS = (
    # Move the opposing palm envelopes 50 mm per side to nominal shell
    # contact. Package-specific targets add their measured preload below.
    (-0.100, -0.053108, -0.4800, -1.5707963267948966, -1.5707963267948966, 0.0),
    (0.130, 0.114808, -0.4311, -1.5707963267948966, 1.5707963267948966, 0.0),
)
HAND_STAGE_FLIP_STABILIZE_TARGETS = HAND_STAGE_FLIP_GRIP_TARGETS
# This is deliberately a stationary pre-roll hold: gravity and the worktable
# support the parcel while the two palm envelopes maintain side preload.
HAND_STAGE_FLIP_LIFT_TARGETS = HAND_STAGE_FLIP_STABILIZE_TARGETS
HAND_STAGE_FLIPPED_LIFT_TARGETS = (
    # Exact end points of a low middle-fingertip pivot path. The asymmetric
    # Z offsets keep both CAD hands wrapped around the parcel as it rolls on
    # the table instead of lifting it into an unsupported free-space turn.
    (-0.100, 0.057308, -0.385890, -4.71238898038469, -1.5707963267948966, 0.0),
    (0.130, 0.040192, -0.487790, -4.71238898038469, 1.5707963267948966, 0.0),
)
HAND_STAGE_FLIP_PLACE_TARGETS = (
    # Hold the completed table-supported roll until residual angular velocity
    # has decayed, then open the fingers without moving either wrist.
    (-0.100, 0.057308, -0.385890, -4.71238898038469, -1.5707963267948966, 0.0),
    (0.130, 0.040192, -0.487790, -4.71238898038469, 1.5707963267948966, 0.0),
)
HAND_STAGE_FLIP_RELEASE_TARGETS = (
    # At the -270 degree equivalent of +90, opening retracts the fingers
    # outward and upward, so the wrists can remain still while the overturned
    # mailer is released.
    (-0.100, 0.057308, -0.385890, -4.71238898038469, -1.5707963267948966, 0.0),
    (0.130, 0.040192, -0.487790, -4.71238898038469, 1.5707963267948966, 0.0),
)
HAND_STAGE_FLIP_CLEAR_TARGETS = (
    (-0.30, 0.057308, -0.12, -4.71238898038469, -1.5707963267948966, 0.0),
    (0.32, 0.040192, -0.22, -4.71238898038469, 1.5707963267948966, 0.0),
)
BLUE_POST_FLIP_ROLL = -2.0 * math.pi
HAND_STAGE_REORIENT_TARGETS = (
    (-0.12, -0.04, 0.08, BLUE_POST_FLIP_ROLL, 0.0, 0.0),
    (0.12, -0.11, 0.08, BLUE_POST_FLIP_ROLL, 0.0, 0.0),
)
HAND_STAGE_PUSH_APPROACH_TARGETS = (
    # Keep a light fingertip preload on the settled shell. Driving the wrists
    # 15 mm lower makes the final approach fight dense shell self-contact and
    # can exhaust Newton iterations without improving the horizontal push.
    (0.0, -0.08, -0.325, BLUE_POST_FLIP_ROLL, 0.0, 0.0),
    (0.0, -0.1505, -0.2985, BLUE_POST_FLIP_ROLL, 0.0, 0.0),
)
HAND_STAGE_PUSH_TARGETS = (
    (0.0, 0.50, -0.325, BLUE_POST_FLIP_ROLL, 0.0, 0.0),
    (0.0, 0.4295, -0.2985, BLUE_POST_FLIP_ROLL, 0.0, 0.0),
)
HAND_STAGE_PUSH_CLEAR_TARGETS = (
    (0.0, 0.50, -0.05, BLUE_POST_FLIP_ROLL, 0.0, 0.0),
    (0.0, 0.4295, -0.0235, BLUE_POST_FLIP_ROLL, 0.0, 0.0),
)


def _retarget_flip_targets(
    targets: tuple[tuple[float, ...], ...],
    *,
    x_shift: float,
    y_shift: float,
    z_shift: float,
    width_inset: float,
    roll_offset: float,
) -> tuple[tuple[float, ...], ...]:
    return tuple(
        (
            target[0] + x_shift + (width_inset if index == 0 else -width_inset),
            target[1] + y_shift,
            target[2] + z_shift,
            target[3] + roll_offset,
            target[4],
            target[5],
        )
        for index, target in enumerate(targets)
    )


def _high_transfer_targets(
    targets: tuple[tuple[float, ...], ...],
) -> tuple[tuple[float, ...], ...]:
    """Keep lateral/rotational targeting while moving both wrists high."""
    return tuple(
        (target[0], target[1], 0.15, *target[3:]) for target in targets
    )


def _limit_side_preload(
    targets: tuple[tuple[float, ...], ...],
    approach: tuple[tuple[float, ...], ...],
    preload: float,
) -> tuple[tuple[float, ...], ...]:
    return tuple(
        (
            approach_target[0] + (preload if index == 0 else -preload),
            *target[1:],
        )
        for index, (target, approach_target) in enumerate(
            zip(targets, approach, strict=True)
        )
    )


def _offset_hand_targets(
    targets: tuple[tuple[float, ...], ...],
    offsets: tuple[tuple[float, ...], ...],
) -> tuple[tuple[float, ...], ...]:
    """Apply an independent Cartesian offset to each wrist target."""
    return tuple(
        tuple(
            value + offset
            for value, offset in zip(target, hand_offset, strict=True)
        )
        for target, hand_offset in zip(targets, offsets, strict=True)
    )


# The blue mailer starts 420 mm deeper on the table than the old edge-adjacent
# pose. The additional 60 mm rearward hand bias puts the fingertip rows behind
# its centerline; measured IPC runs otherwise squeeze the loose film backward
# before the wrist roll begins.
BLUE_FLIP_Y_SHIFT = -0.480
_BLUE_FLIP_BIASES = (
    (-0.030, BLUE_FLIP_Y_SHIFT, -0.050, 0.0, 0.0, 0.0),
    (0.0, BLUE_FLIP_Y_SHIFT, -0.050, 0.0, 0.0, 0.0),
)
HAND_STAGE_BLUE_FLIP_APPROACH_TARGETS = _offset_hand_targets(
    HAND_STAGE_FLIP_APPROACH_TARGETS,
    _BLUE_FLIP_BIASES,
)
HAND_STAGE_BLUE_FLIP_CONTACT_TARGETS = _offset_hand_targets(
    HAND_STAGE_FLIP_GRIP_TARGETS,
    _BLUE_FLIP_BIASES,
)
BLUE_FLIP_PALM_PRELOAD = 0.015
HAND_STAGE_BLUE_FLIP_GRIP_TARGETS = _limit_side_preload(
    HAND_STAGE_BLUE_FLIP_CONTACT_TARGETS,
    HAND_STAGE_BLUE_FLIP_CONTACT_TARGETS,
    BLUE_FLIP_PALM_PRELOAD,
)
HAND_STAGE_BLUE_FLIP_STABILIZE_TARGETS = HAND_STAGE_BLUE_FLIP_GRIP_TARGETS
BLUE_FLIP_FOLLOW_THROUGH = 0.180
HAND_STAGE_BLUE_FLIPPED_TARGETS = _offset_hand_targets(
    _limit_side_preload(
        _offset_hand_targets(
            HAND_STAGE_FLIPPED_LIFT_TARGETS,
            _BLUE_FLIP_BIASES,
        ),
        HAND_STAGE_BLUE_FLIP_CONTACT_TARGETS,
        BLUE_FLIP_PALM_PRELOAD,
    ),
    (
        (0.0, BLUE_FLIP_FOLLOW_THROUGH, 0.0, 0.0, 0.0, 0.0),
        (0.0, BLUE_FLIP_FOLLOW_THROUGH, 0.0, 0.0, 0.0, 0.0),
    ),
)
HAND_STAGE_BLUE_FLIP_RELEASE_TARGETS = HAND_STAGE_BLUE_FLIPPED_TARGETS
HAND_STAGE_BLUE_FLIP_CLEAR_TARGETS = _offset_hand_targets(
    HAND_STAGE_BLUE_FLIP_RELEASE_TARGETS,
    (
        (-0.200, 0.0, 0.120, 0.0, 0.0, 0.0),
        (0.200, 0.0, 0.120, 0.0, 0.0, 0.0),
    ),
)

YELLOW_FLIP_X_SHIFT = -0.66
YELLOW_FLIP_Y_SHIFT = 0.010
YELLOW_FLIP_Z_SHIFT = -0.059
YELLOW_FLIP_ROLL_OFFSET = -2.0 * math.pi
# The yellow pouch is 150 mm narrower than the blue mailer. Move each wrist
# inward by half that difference so both fingertip rows still preload its seam.
YELLOW_FLIP_WIDTH_INSET = 0.075
YELLOW_FLIP_RIGHT_APPROACH_CLEARANCE = 0.090
HAND_STAGE_YELLOW_FLIP_CONTACT_TARGETS = _retarget_flip_targets(
    HAND_STAGE_FLIP_APPROACH_TARGETS,
    x_shift=YELLOW_FLIP_X_SHIFT,
    y_shift=YELLOW_FLIP_Y_SHIFT,
    z_shift=YELLOW_FLIP_Z_SHIFT,
    width_inset=YELLOW_FLIP_WIDTH_INSET,
    roll_offset=YELLOW_FLIP_ROLL_OFFSET,
)
HAND_STAGE_YELLOW_FLIP_APPROACH_TARGETS = _offset_hand_targets(
    HAND_STAGE_YELLOW_FLIP_CONTACT_TARGETS,
    (
        (0.0, 0.0, 0.0, 0.0, 0.0, 0.0),
        (YELLOW_FLIP_RIGHT_APPROACH_CLEARANCE, 0.0, 0.0, 0.0, 0.0, 0.0),
    ),
)
HAND_STAGE_YELLOW_FLIP_TRANSFER_TARGETS = _high_transfer_targets(
    HAND_STAGE_YELLOW_FLIP_APPROACH_TARGETS
)
HAND_STAGE_BLUE_PUSH_DEPART_TARGETS = _high_transfer_targets(
    HAND_STAGE_PUSH_CLEAR_TARGETS
)
YELLOW_FLIP_PALM_PRELOAD = 0.015
HAND_STAGE_YELLOW_FLIP_GRIP_TARGETS = _limit_side_preload(
    _retarget_flip_targets(
        HAND_STAGE_FLIP_GRIP_TARGETS,
        x_shift=YELLOW_FLIP_X_SHIFT,
        y_shift=YELLOW_FLIP_Y_SHIFT,
        z_shift=YELLOW_FLIP_Z_SHIFT,
        width_inset=YELLOW_FLIP_WIDTH_INSET,
        roll_offset=YELLOW_FLIP_ROLL_OFFSET,
    ),
    HAND_STAGE_YELLOW_FLIP_CONTACT_TARGETS,
    YELLOW_FLIP_PALM_PRELOAD,
)
HAND_STAGE_YELLOW_FLIP_STABILIZE_TARGETS = (
    HAND_STAGE_YELLOW_FLIP_GRIP_TARGETS
)
YELLOW_FLIP_FOLLOW_THROUGH = 0.180
HAND_STAGE_YELLOW_FLIPPED_TARGETS = _offset_hand_targets(
    _retarget_flip_targets(
        HAND_STAGE_FLIPPED_LIFT_TARGETS,
        x_shift=YELLOW_FLIP_X_SHIFT,
        y_shift=YELLOW_FLIP_Y_SHIFT,
        z_shift=YELLOW_FLIP_Z_SHIFT,
        width_inset=YELLOW_FLIP_WIDTH_INSET,
        roll_offset=YELLOW_FLIP_ROLL_OFFSET,
    ),
    (
        # The dense pouch advances while it rolls. Following it by 180 mm keeps
        # both fingertip rows on the upper seam through the full table-supported
        # turn; without this translation the hands lag behind and lose contact
        # shortly after the pouch passes vertical.
        (0.0, YELLOW_FLIP_FOLLOW_THROUGH, 0.0, 0.0, 0.0, 0.0),
        (0.0, YELLOW_FLIP_FOLLOW_THROUGH, 0.0, 0.0, 0.0, 0.0),
    ),
)
HAND_STAGE_YELLOW_FLIP_RELEASE_TARGETS = HAND_STAGE_YELLOW_FLIPPED_TARGETS
HAND_STAGE_YELLOW_FLIP_CLEAR_TARGETS = _offset_hand_targets(
    HAND_STAGE_YELLOW_FLIP_RELEASE_TARGETS,
    (
        (-0.200, 0.0, 0.120, 0.0, 0.0, 0.0),
        (0.200, 0.0, 0.120, 0.0, 0.0, 0.0),
    ),
)

CARTON_FLIP_X_SHIFT = -1.18
CARTON_FLIP_Y_SHIFT = -0.030
CARTON_FLIP_Z_SHIFT = 0.035
CARTON_FLIP_ROLL_OFFSET = -4.0 * math.pi
CARTON_FLIP_WIDTH_INSET = 0.095
HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS = _retarget_flip_targets(
    HAND_STAGE_FLIP_APPROACH_TARGETS,
    x_shift=CARTON_FLIP_X_SHIFT,
    y_shift=CARTON_FLIP_Y_SHIFT,
    z_shift=CARTON_FLIP_Z_SHIFT,
    width_inset=CARTON_FLIP_WIDTH_INSET,
    roll_offset=CARTON_FLIP_ROLL_OFFSET,
)
HAND_STAGE_CARTON_FLIP_TRANSFER_TARGETS = _high_transfer_targets(
    HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS
)
HAND_STAGE_YELLOW_FLIP_DEPART_TARGETS = _high_transfer_targets(
    HAND_STAGE_YELLOW_FLIP_CLEAR_TARGETS
)
CARTON_FLIP_PALM_PRELOAD = 0.002
HAND_STAGE_CARTON_FLIP_GRIP_TARGETS = _limit_side_preload(
    _retarget_flip_targets(
        HAND_STAGE_FLIP_GRIP_TARGETS,
        x_shift=CARTON_FLIP_X_SHIFT,
        y_shift=CARTON_FLIP_Y_SHIFT,
        z_shift=CARTON_FLIP_Z_SHIFT,
        width_inset=CARTON_FLIP_WIDTH_INSET,
        roll_offset=CARTON_FLIP_ROLL_OFFSET,
    ),
    HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS,
    CARTON_FLIP_PALM_PRELOAD,
)
HAND_STAGE_CARTON_FLIP_STABILIZE_TARGETS = _limit_side_preload(
    _retarget_flip_targets(
        HAND_STAGE_FLIP_STABILIZE_TARGETS,
        x_shift=CARTON_FLIP_X_SHIFT,
        y_shift=CARTON_FLIP_Y_SHIFT,
        z_shift=CARTON_FLIP_Z_SHIFT,
        width_inset=CARTON_FLIP_WIDTH_INSET,
        roll_offset=CARTON_FLIP_ROLL_OFFSET,
    ),
    HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS,
    CARTON_FLIP_PALM_PRELOAD,
)
HAND_STAGE_CARTON_FLIP_LIFT_TARGETS = _limit_side_preload(
    _retarget_flip_targets(
        HAND_STAGE_FLIP_LIFT_TARGETS,
        x_shift=CARTON_FLIP_X_SHIFT,
        y_shift=CARTON_FLIP_Y_SHIFT,
        z_shift=CARTON_FLIP_Z_SHIFT,
        width_inset=CARTON_FLIP_WIDTH_INSET,
        roll_offset=CARTON_FLIP_ROLL_OFFSET,
    ),
    HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS,
    CARTON_FLIP_PALM_PRELOAD,
)
HAND_STAGE_CARTON_FLIPPED_LIFT_TARGETS = _limit_side_preload(
    _retarget_flip_targets(
        HAND_STAGE_FLIPPED_LIFT_TARGETS,
        x_shift=CARTON_FLIP_X_SHIFT,
        y_shift=CARTON_FLIP_Y_SHIFT,
        z_shift=CARTON_FLIP_Z_SHIFT,
        width_inset=CARTON_FLIP_WIDTH_INSET,
        roll_offset=CARTON_FLIP_ROLL_OFFSET,
    ),
    HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS,
    CARTON_FLIP_PALM_PRELOAD,
)
CARTON_FLIP_PLACE_DROP = 0.080
HAND_STAGE_CARTON_FLIP_PLACE_TARGETS = tuple(
    (
        target[0],
        target[1],
        target[2] - CARTON_FLIP_PLACE_DROP,
        *target[3:],
    )
    for target in HAND_STAGE_CARTON_FLIPPED_LIFT_TARGETS
)
HAND_STAGE_CARTON_FLIP_RELEASE_TARGETS = (
    HAND_STAGE_CARTON_FLIP_PLACE_TARGETS
)
# The left stage is already close to its -1.24 m travel limit at this upstream
# carton. Open the fingers, keep that palm at the limit, and withdraw the right
# palm by 200 mm before either hand rises. This measured sequence leaves the
# inverted carton resting on the table instead of sweeping it upward.
HAND_STAGE_CARTON_FLIP_CLEAR_TARGETS = tuple(
    (
        max(-1.24, target[0] - 0.20)
        if index == 0
        else min(1.24, target[0] + 0.20),
        *target[1:],
    )
    for index, target in enumerate(HAND_STAGE_CARTON_FLIP_RELEASE_TARGETS)
)
HAND_STAGE_CARTON_FLIP_DEPART_TARGETS = _high_transfer_targets(
    HAND_STAGE_CARTON_FLIP_CLEAR_TARGETS
)

HAND_STAGE_RETURN_TARGETS = (
    (0.0, 0.0, 0.0, -6.0 * math.pi, 0.0, 0.0),
    (0.0, 0.0, 0.0, -6.0 * math.pi, 0.0, 0.0),
)

LEAP_FINGER_CLOSE_TARGETS = (
    1.08, 0.0, 0.82, 0.78,
    1.08, 0.0, 0.82, 0.78,
    1.08, 0.0, 0.82, 0.78,
    0.82, 0.50, 0.82, 0.78,
)
PUSH_FINGER_CLOSE_FRACTION = 0.30
# Both flexible packages use a symmetric seam pinch so neither hand becomes a
# stationary visual pivot while the other hand carries the whole parcel.
BLUE_FLIP_FINGER_CLOSE_FRACTIONS = (0.45, 0.45)
YELLOW_FLIP_FINGER_CLOSE_FRACTIONS = (0.45, 0.45)
CARTON_FLIP_FINGER_CLOSE_FRACTION = 0.15


@dataclass(frozen=True)
class HandMotionSegment:
    phase: str
    duration: int
    start: tuple[tuple[float, ...], ...]
    end: tuple[tuple[float, ...], ...]
    close_start: float | tuple[float, float] = 0.0
    close_end: float | tuple[float, float] = 0.0
    pivot_roll: bool = False


HAND_MOTION_SEGMENTS = (
    HandMotionSegment(
        "drop_settle", DROP_SETTLE_TICKS,
        HAND_STAGE_HOME_TARGETS, HAND_STAGE_HOME_TARGETS,
    ),
    HandMotionSegment(
        "blue_flip_approach", FLIP_APPROACH_TICKS,
        HAND_STAGE_HOME_TARGETS, HAND_STAGE_BLUE_FLIP_APPROACH_TARGETS,
    ),
    HandMotionSegment(
        "blue_flip_contact", FLIP_CONTACT_TICKS,
        HAND_STAGE_BLUE_FLIP_APPROACH_TARGETS,
        HAND_STAGE_BLUE_FLIP_CONTACT_TARGETS,
    ),
    HandMotionSegment(
        "blue_flip_grip", FLIP_GRIP_TICKS,
        HAND_STAGE_BLUE_FLIP_CONTACT_TARGETS,
        HAND_STAGE_BLUE_FLIP_GRIP_TARGETS,
        0.0, BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "blue_flip_stabilize", FLIP_STABILIZE_TICKS,
        HAND_STAGE_BLUE_FLIP_GRIP_TARGETS,
        HAND_STAGE_BLUE_FLIP_STABILIZE_TARGETS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "blue_flip_rotate", FLIP_ROTATE_TICKS,
        HAND_STAGE_BLUE_FLIP_STABILIZE_TARGETS,
        HAND_STAGE_BLUE_FLIPPED_TARGETS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS,
        True,
    ),
    HandMotionSegment(
        "blue_flip_release", FLIP_RELEASE_TICKS,
        HAND_STAGE_BLUE_FLIPPED_TARGETS,
        HAND_STAGE_BLUE_FLIP_RELEASE_TARGETS,
        BLUE_FLIP_FINGER_CLOSE_FRACTIONS, 0.0,
    ),
    HandMotionSegment(
        "blue_flip_clear", FLIP_CLEAR_TICKS,
        HAND_STAGE_BLUE_FLIP_RELEASE_TARGETS,
        HAND_STAGE_BLUE_FLIP_CLEAR_TARGETS,
    ),
    HandMotionSegment(
        "blue_flip_settle", FLIP_SETTLE_TICKS,
        HAND_STAGE_BLUE_FLIP_CLEAR_TARGETS,
        HAND_STAGE_BLUE_FLIP_CLEAR_TARGETS,
    ),
    HandMotionSegment(
        "blue_reorient", REORIENT_TICKS,
        HAND_STAGE_BLUE_FLIP_CLEAR_TARGETS, HAND_STAGE_REORIENT_TARGETS,
    ),
    HandMotionSegment(
        "blue_push_approach", PUSH_APPROACH_TICKS,
        HAND_STAGE_REORIENT_TARGETS, HAND_STAGE_PUSH_APPROACH_TARGETS,
        0.0, PUSH_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "blue_push", PUSH_TICKS,
        HAND_STAGE_PUSH_APPROACH_TARGETS, HAND_STAGE_PUSH_TARGETS,
        PUSH_FINGER_CLOSE_FRACTION, PUSH_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "blue_push_release", PUSH_RELEASE_TICKS,
        HAND_STAGE_PUSH_TARGETS, HAND_STAGE_PUSH_TARGETS,
        PUSH_FINGER_CLOSE_FRACTION, 0.0,
    ),
    HandMotionSegment(
        "blue_push_clear", PUSH_CLEAR_TICKS,
        HAND_STAGE_PUSH_TARGETS, HAND_STAGE_PUSH_CLEAR_TARGETS,
    ),
    HandMotionSegment(
        "blue_push_depart", YELLOW_FLIP_DEPART_TICKS,
        HAND_STAGE_PUSH_CLEAR_TARGETS, HAND_STAGE_BLUE_PUSH_DEPART_TARGETS,
    ),
    HandMotionSegment(
        "yellow_flip_transfer", YELLOW_FLIP_TRANSFER_TICKS,
        HAND_STAGE_BLUE_PUSH_DEPART_TARGETS,
        HAND_STAGE_YELLOW_FLIP_TRANSFER_TARGETS,
    ),
    HandMotionSegment(
        "yellow_flip_approach", YELLOW_FLIP_APPROACH_TICKS,
        HAND_STAGE_YELLOW_FLIP_TRANSFER_TARGETS,
        HAND_STAGE_YELLOW_FLIP_APPROACH_TARGETS,
    ),
    HandMotionSegment(
        "yellow_flip_contact", YELLOW_FLIP_CONTACT_TICKS,
        HAND_STAGE_YELLOW_FLIP_APPROACH_TARGETS,
        HAND_STAGE_YELLOW_FLIP_CONTACT_TARGETS,
    ),
    HandMotionSegment(
        "yellow_flip_grip", YELLOW_FLIP_GRIP_TICKS,
        HAND_STAGE_YELLOW_FLIP_CONTACT_TARGETS,
        HAND_STAGE_YELLOW_FLIP_GRIP_TARGETS,
        0.0, YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "yellow_flip_stabilize", YELLOW_FLIP_STABILIZE_TICKS,
        HAND_STAGE_YELLOW_FLIP_GRIP_TARGETS,
        HAND_STAGE_YELLOW_FLIP_STABILIZE_TARGETS,
        YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
        YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
    ),
    HandMotionSegment(
        "yellow_flip_rotate", YELLOW_FLIP_ROTATE_TICKS,
        HAND_STAGE_YELLOW_FLIP_STABILIZE_TARGETS,
        HAND_STAGE_YELLOW_FLIPPED_TARGETS,
        YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
        YELLOW_FLIP_FINGER_CLOSE_FRACTIONS,
        True,
    ),
    HandMotionSegment(
        "yellow_flip_release", YELLOW_FLIP_RELEASE_TICKS,
        HAND_STAGE_YELLOW_FLIPPED_TARGETS,
        HAND_STAGE_YELLOW_FLIP_RELEASE_TARGETS,
        YELLOW_FLIP_FINGER_CLOSE_FRACTIONS, 0.0,
    ),
    HandMotionSegment(
        "yellow_flip_clear", YELLOW_FLIP_CLEAR_TICKS,
        HAND_STAGE_YELLOW_FLIP_RELEASE_TARGETS,
        HAND_STAGE_YELLOW_FLIP_CLEAR_TARGETS,
    ),
    HandMotionSegment(
        "yellow_flip_settle", YELLOW_FLIP_SETTLE_TICKS,
        HAND_STAGE_YELLOW_FLIP_CLEAR_TARGETS,
        HAND_STAGE_YELLOW_FLIP_CLEAR_TARGETS,
    ),
    HandMotionSegment(
        "yellow_flip_depart", CARTON_FLIP_DEPART_TICKS,
        HAND_STAGE_YELLOW_FLIP_CLEAR_TARGETS,
        HAND_STAGE_YELLOW_FLIP_DEPART_TARGETS,
    ),
    HandMotionSegment(
        "carton_flip_transfer", CARTON_FLIP_TRANSFER_TICKS,
        HAND_STAGE_YELLOW_FLIP_DEPART_TARGETS,
        HAND_STAGE_CARTON_FLIP_TRANSFER_TARGETS,
    ),
    HandMotionSegment(
        "carton_flip_approach", CARTON_FLIP_APPROACH_TICKS,
        HAND_STAGE_CARTON_FLIP_TRANSFER_TARGETS,
        HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS,
    ),
    HandMotionSegment(
        "carton_flip_grip", CARTON_FLIP_GRIP_TICKS,
        HAND_STAGE_CARTON_FLIP_APPROACH_TARGETS,
        HAND_STAGE_CARTON_FLIP_GRIP_TARGETS,
        0.0, CARTON_FLIP_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "carton_flip_stabilize", CARTON_FLIP_STABILIZE_TICKS,
        HAND_STAGE_CARTON_FLIP_GRIP_TARGETS,
        HAND_STAGE_CARTON_FLIP_STABILIZE_TARGETS,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "carton_flip_lift", CARTON_FLIP_LIFT_TICKS,
        HAND_STAGE_CARTON_FLIP_STABILIZE_TARGETS,
        HAND_STAGE_CARTON_FLIP_LIFT_TARGETS,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "carton_flip_rotate", CARTON_FLIP_ROTATE_TICKS,
        HAND_STAGE_CARTON_FLIP_LIFT_TARGETS,
        HAND_STAGE_CARTON_FLIPPED_LIFT_TARGETS,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
        True,
    ),
    HandMotionSegment(
        "carton_flip_place", CARTON_FLIP_PLACE_TICKS,
        HAND_STAGE_CARTON_FLIPPED_LIFT_TARGETS,
        HAND_STAGE_CARTON_FLIP_PLACE_TARGETS,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
        CARTON_FLIP_FINGER_CLOSE_FRACTION,
    ),
    HandMotionSegment(
        "carton_flip_release", CARTON_FLIP_RELEASE_TICKS,
        HAND_STAGE_CARTON_FLIP_PLACE_TARGETS,
        HAND_STAGE_CARTON_FLIP_RELEASE_TARGETS,
        CARTON_FLIP_FINGER_CLOSE_FRACTION, 0.0,
    ),
    HandMotionSegment(
        "carton_flip_clear", CARTON_FLIP_CLEAR_TICKS,
        HAND_STAGE_CARTON_FLIP_RELEASE_TARGETS,
        HAND_STAGE_CARTON_FLIP_CLEAR_TARGETS,
    ),
    HandMotionSegment(
        "carton_flip_depart", CARTON_FLIP_RAISE_TICKS,
        HAND_STAGE_CARTON_FLIP_CLEAR_TARGETS,
        HAND_STAGE_CARTON_FLIP_DEPART_TARGETS,
    ),
    HandMotionSegment(
        "return_home", RETURN_HOME_TICKS,
        HAND_STAGE_CARTON_FLIP_DEPART_TARGETS, HAND_STAGE_RETURN_TARGETS,
    ),
)
MANIPULATION_TICKS = sum(segment.duration for segment in HAND_MOTION_SEGMENTS)
RAMP_TICKS = 80
CONVEY_TICKS = 180
BRAKE_TICKS = 160
HOLD_TICKS = 240
_BLUE_PUSH_SEGMENT_INDEX = next(
    index
    for index, segment in enumerate(HAND_MOTION_SEGMENTS)
    if segment.phase == "blue_push"
)
BELT_START_TICKS = sum(
    segment.duration
    for segment in HAND_MOTION_SEGMENTS[: _BLUE_PUSH_SEGMENT_INDEX + 1]
)
CYCLE_TICKS = max(
    MANIPULATION_TICKS,
    BELT_START_TICKS + RAMP_TICKS + CONVEY_TICKS + BRAKE_TICKS,
) + HOLD_TICKS
QUALITY_ENVIRONMENT_VARIABLE = "GOBOT_CONVEYOR_QUALITY"


@dataclass(frozen=True)
class ConveyorQualityProfile:
    name: str
    coupling_iterations: int
    relaxation_mode: str
    scene_sync_interval: int
    contact_refresh_interval: int
    newton_max_iterations: int
    line_search_max_iterations: int
    linear_system_tolerance_rate: float
    strict_convergence: bool


QUALITY_PROFILES = {
    "interactive": ConveyorQualityProfile(
        name="interactive",
        coupling_iterations=1,
        relaxation_mode="fixed",
        scene_sync_interval=2,
        contact_refresh_interval=4,
        # The thin shell repeatedly enters dense finger contact while it is
        # flipped. Most frames converge within 12 iterations, but the contact
        # transitions need more nonlinear iterations to reach the same 0.1 mm
        # displacement tolerance. Keep the faster interactive linear solve;
        # Newton exits early on ordinary frames, so this is only a safety cap.
        # Ordinary frames still exit at convergence. The higher cap is only
        # reached by rare film/fingertip topology changes during a turnover;
        # 32 iterations left two unconverged frames in a 2,960-step GPU run.
        newton_max_iterations=48,
        line_search_max_iterations=8,
        linear_system_tolerance_rate=2.0e-3,
        strict_convergence=False,
    ),
    "accurate": ConveyorQualityProfile(
        name="accurate",
        coupling_iterations=2,
        relaxation_mode="aitken",
        scene_sync_interval=1,
        contact_refresh_interval=1,
        newton_max_iterations=16,
        line_search_max_iterations=8,
        linear_system_tolerance_rate=1.0e-3,
        strict_convergence=True,
    ),
}


def quality_profile(name: str | None = None) -> ConveyorQualityProfile:
    selected = (
        name
        if name is not None
        else os.environ.get(QUALITY_ENVIRONMENT_VARIABLE, "interactive")
    )
    selected = str(selected).strip().lower()
    try:
        return QUALITY_PROFILES[selected]
    except KeyError as error:
        choices = ", ".join(repr(value) for value in QUALITY_PROFILES)
        raise ValueError(
            f"{QUALITY_ENVIRONMENT_VARIABLE} must be one of {choices}"
        ) from error


def smoothstep(value: float) -> float:
    value = max(0.0, min(1.0, float(value)))
    return value * value * (3.0 - 2.0 * value)


def belt_speed_at_tick(tick: int) -> float:
    tick = max(0, int(tick))
    if tick < BELT_START_TICKS:
        return 0.0
    tick -= BELT_START_TICKS
    if tick < RAMP_TICKS:
        return BELT_SPEED * smoothstep(float(tick + 1) / RAMP_TICKS)
    tick -= RAMP_TICKS
    if tick < CONVEY_TICKS:
        return BELT_SPEED
    tick -= CONVEY_TICKS
    if tick < BRAKE_TICKS:
        return BELT_SPEED * (
            1.0 - smoothstep(float(tick + 1) / BRAKE_TICKS)
        )
    return 0.0


def _lerp_targets(
    start: tuple[tuple[float, ...], ...],
    end: tuple[tuple[float, ...], ...],
    fraction: float,
) -> tuple[tuple[float, ...], ...]:
    return tuple(
        tuple(
            start_value + (end_value - start_value) * fraction
            for start_value, end_value in zip(
                start_hand, end_hand, strict=True
            )
        )
        for start_hand, end_hand in zip(start, end, strict=True)
    )


def _transition(
    tick: int,
    duration: int,
    start: tuple[tuple[float, ...], ...],
    end: tuple[tuple[float, ...], ...],
) -> tuple[tuple[float, ...], ...]:
    fraction = smoothstep(float(tick + 1) / duration)
    return _lerp_targets(start, end, fraction)


def _pivot_roll_transition(
    tick: int,
    duration: int,
    start: tuple[tuple[float, ...], ...],
    end: tuple[tuple[float, ...], ...],
) -> tuple[tuple[float, ...], ...]:
    """Roll each wrist through 180 degrees about a fixed fingertip point."""
    fraction = smoothstep(float(tick + 1) / duration)
    targets = []
    for start_hand, end_hand in zip(start, end, strict=True):
        roll_delta = end_hand[3] - start_hand[3]
        angle = roll_delta * fraction
        cosine = math.cos(angle)
        sine = math.sin(angle)
        pivot_y = 0.5 * (start_hand[1] + end_hand[1])
        pivot_z = 0.5 * (start_hand[2] + end_hand[2])
        offset_y = pivot_y - start_hand[1]
        offset_z = pivot_z - start_hand[2]
        rotated_y = cosine * offset_y - sine * offset_z
        rotated_z = sine * offset_y + cosine * offset_z
        linear = tuple(
            start_value + (end_value - start_value) * fraction
            for start_value, end_value in zip(
                start_hand, end_hand, strict=True
            )
        )
        targets.append(
            (
                linear[0],
                pivot_y - rotated_y,
                pivot_z - rotated_z,
                linear[3],
                linear[4],
                linear[5],
            )
        )
    return tuple(targets)


def _motion_segment_at_tick(
    tick: int,
) -> tuple[HandMotionSegment | None, int]:
    local_tick = max(0, int(tick))
    for segment in HAND_MOTION_SEGMENTS:
        if local_tick < segment.duration:
            return segment, local_tick
        local_tick -= segment.duration
    return None, 0


def hand_stage_targets_at_tick(
    tick: int,
) -> tuple[tuple[float, ...], ...]:
    segment, local_tick = _motion_segment_at_tick(tick)
    if segment is None:
        return HAND_MOTION_SEGMENTS[-1].end
    transition = _pivot_roll_transition if segment.pivot_roll else _transition
    return transition(
        local_tick,
        segment.duration,
        segment.start,
        segment.end,
    )


def _finger_close_pair(
    value: float | tuple[float, float],
) -> tuple[float, float]:
    if isinstance(value, tuple):
        if len(value) != 2:
            raise ValueError("finger close target must contain two hands")
        return (float(value[0]), float(value[1]))
    scalar = float(value)
    return (scalar, scalar)


def finger_close_fractions_at_tick(tick: int) -> tuple[float, float]:
    segment, local_tick = _motion_segment_at_tick(tick)
    if segment is None:
        return (0.0, 0.0)
    fraction = smoothstep(float(local_tick + 1) / segment.duration)
    close_start = _finger_close_pair(segment.close_start)
    close_end = _finger_close_pair(segment.close_end)
    return tuple(
        start + (end - start) * fraction
        for start, end in zip(close_start, close_end, strict=True)
    )


def finger_close_fraction_at_tick(tick: int) -> float:
    """Return the strongest hand closure for compact UI diagnostics."""
    return max(finger_close_fractions_at_tick(tick))


def hand_controls_at_tick(tick: int) -> tuple[tuple[float, ...], ...]:
    stage_targets = hand_stage_targets_at_tick(tick)
    close_fractions = finger_close_fractions_at_tick(tick)
    return tuple(
        stage
        + tuple(
            value * close_fraction for value in LEAP_FINGER_CLOSE_TARGETS
        )
        for stage, close_fraction in zip(
            stage_targets, close_fractions, strict=True
        )
    )


def cycle_phase(tick: int) -> str:
    segment, _ = _motion_segment_at_tick(tick)
    return segment.phase if segment is not None else "settle"
